/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParcelaExpressApi);
  }
}(this, function(expect, ParcelaExpressApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreateBilletDto', function() {
      beforeEach(function() {
        instance = new ParcelaExpressApi.CreateBilletDto();
      });

      it('should create an instance of CreateBilletDto', function() {
        // TODO: update the code to test CreateBilletDto
        expect(instance).to.be.a(ParcelaExpressApi.CreateBilletDto);
      });

      it('should have the property value (base name: "value")', function() {
        // TODO: update the code to test the property value
        expect(instance).to.have.property('value');
        // expect(instance.value).to.be(expectedValueLiteral);
      });

      it('should have the property socialSecurityNumber (base name: "social_security_number")', function() {
        // TODO: update the code to test the property socialSecurityNumber
        expect(instance).to.have.property('socialSecurityNumber');
        // expect(instance.socialSecurityNumber).to.be(expectedValueLiteral);
      });

      it('should have the property shopperStatement (base name: "shopper_statement")', function() {
        // TODO: update the code to test the property shopperStatement
        expect(instance).to.have.property('shopperStatement');
        // expect(instance.shopperStatement).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property deliveryDate (base name: "delivery_date")', function() {
        // TODO: update the code to test the property deliveryDate
        expect(instance).to.have.property('deliveryDate');
        // expect(instance.deliveryDate).to.be(expectedValueLiteral);
      });

      it('should have the property shopper (base name: "shopper")', function() {
        // TODO: update the code to test the property shopper
        expect(instance).to.have.property('shopper');
        // expect(instance.shopper).to.be(expectedValueLiteral);
      });

      it('should have the property saleId (base name: "sale_id")', function() {
        // TODO: update the code to test the property saleId
        expect(instance).to.have.property('saleId');
        // expect(instance.saleId).to.be(expectedValueLiteral);
      });

      it('should have the property protestLink (base name: "protest_link")', function() {
        // TODO: update the code to test the property protestLink
        expect(instance).to.have.property('protestLink');
        // expect(instance.protestLink).to.be(expectedValueLiteral);
      });

      it('should have the property amountFee (base name: "amount_fee")', function() {
        // TODO: update the code to test the property amountFee
        expect(instance).to.have.property('amountFee');
        // expect(instance.amountFee).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property hasSplitRules (base name: "has_split_rules")', function() {
        // TODO: update the code to test the property hasSplitRules
        expect(instance).to.have.property('hasSplitRules');
        // expect(instance.hasSplitRules).to.be(expectedValueLiteral);
      });

      it('should have the property splitRules (base name: "split_rules")', function() {
        // TODO: update the code to test the property splitRules
        expect(instance).to.have.property('splitRules');
        // expect(instance.splitRules).to.be(expectedValueLiteral);
      });

      it('should have the property metadata (base name: "metadata")', function() {
        // TODO: update the code to test the property metadata
        expect(instance).to.have.property('metadata');
        // expect(instance.metadata).to.be(expectedValueLiteral);
      });

    });
  });

}));
