/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParcelaExpressApi);
  }
}(this, function(expect, ParcelaExpressApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ParcelaExpressApi.CreatePaymentDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreatePaymentDto', function() {
    it('should create an instance of CreatePaymentDto', function() {
      // uncomment below and update the code to test CreatePaymentDto
      //var instane = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be.a(ParcelaExpressApi.CreatePaymentDto);
    });

    it('should have the property amount_cents (base name: "amount_cents")', function() {
      // uncomment below and update the code to test the property amount_cents
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property card_attributes (base name: "card_attributes")', function() {
      // uncomment below and update the code to test the property card_attributes
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property installment_plan (base name: "installment_plan")', function() {
      // uncomment below and update the code to test the property installment_plan
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property customer (base name: "customer")', function() {
      // uncomment below and update the code to test the property customer
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property pre_capture (base name: "pre_capture")', function() {
      // uncomment below and update the code to test the property pre_capture
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property form_payment (base name: "form_payment")', function() {
      // uncomment below and update the code to test the property form_payment
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property success_return_url (base name: "success_return_url")', function() {
      // uncomment below and update the code to test the property success_return_url
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property error_return_url (base name: "error_return_url")', function() {
      // uncomment below and update the code to test the property error_return_url
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property recurrence (base name: "recurrence")', function() {
      // uncomment below and update the code to test the property recurrence
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property recurrence_day (base name: "recurrence_day")', function() {
      // uncomment below and update the code to test the property recurrence_day
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property sale_id (base name: "sale_id")', function() {
      // uncomment below and update the code to test the property sale_id
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property protest_link (base name: "protest_link")', function() {
      // uncomment below and update the code to test the property protest_link
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property amount_fee (base name: "amount_fee")', function() {
      // uncomment below and update the code to test the property amount_fee
      //var instance = new ParcelaExpressApi.CreatePaymentDto();
      //expect(instance).to.be();
    });

  });

}));
