/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParcelaExpressApi);
  }
}(this, function(expect, ParcelaExpressApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreatePixPaymentWithSplitInternalDto', function() {
    it('should create an instance of CreatePixPaymentWithSplitInternalDto', function() {
      // uncomment below and update the code to test CreatePixPaymentWithSplitInternalDto
      //var instane = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
      //expect(instance).to.be.a(ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto);
    });

    it('should have the property amount_cents (base name: "amount_cents")', function() {
      // uncomment below and update the code to test the property amount_cents
      //var instance = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
      //expect(instance).to.be();
    });

    it('should have the property customer (base name: "customer")', function() {
      // uncomment below and update the code to test the property customer
      //var instance = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
      //expect(instance).to.be();
    });

    it('should have the property sale_id (base name: "sale_id")', function() {
      // uncomment below and update the code to test the property sale_id
      //var instance = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
      //expect(instance).to.be();
    });

    it('should have the property protest_link (base name: "protest_link")', function() {
      // uncomment below and update the code to test the property protest_link
      //var instance = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
      //expect(instance).to.be();
    });

    it('should have the property amount_fee (base name: "amount_fee")', function() {
      // uncomment below and update the code to test the property amount_fee
      //var instance = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
      //expect(instance).to.be();
    });

    it('should have the property has_split_rules (base name: "has_split_rules")', function() {
      // uncomment below and update the code to test the property has_split_rules
      //var instance = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
      //expect(instance).to.be();
    });

    it('should have the property split_rules (base name: "split_rules")', function() {
      // uncomment below and update the code to test the property split_rules
      //var instance = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
      //expect(instance).to.be();
    });

    it('should have the property confirmation_required (base name: "confirmation_required")', function() {
      // uncomment below and update the code to test the property confirmation_required
      //var instance = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
      //expect(instance).to.be();
    });

    it('should have the property extract_identification (base name: "extract_identification")', function() {
      // uncomment below and update the code to test the property extract_identification
      //var instance = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
      //expect(instance).to.be();
    });

    it('should have the property service_id (base name: "service_id")', function() {
      // uncomment below and update the code to test the property service_id
      //var instance = new ParcelaExpressApi.CreatePixPaymentWithSplitInternalDto();
      //expect(instance).to.be();
    });

  });

}));
