/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParcelaExpressApi);
  }
}(this, function(expect, ParcelaExpressApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreatePixPaymentDto', function() {
      beforeEach(function() {
        instance = new ParcelaExpressApi.CreatePixPaymentDto();
      });

      it('should create an instance of CreatePixPaymentDto', function() {
        // TODO: update the code to test CreatePixPaymentDto
        expect(instance).to.be.a(ParcelaExpressApi.CreatePixPaymentDto);
      });

      it('should have the property amountCents (base name: "amount_cents")', function() {
        // TODO: update the code to test the property amountCents
        expect(instance).to.have.property('amountCents');
        // expect(instance.amountCents).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property customer (base name: "customer")', function() {
        // TODO: update the code to test the property customer
        expect(instance).to.have.property('customer');
        // expect(instance.customer).to.be(expectedValueLiteral);
      });

      it('should have the property saleId (base name: "sale_id")', function() {
        // TODO: update the code to test the property saleId
        expect(instance).to.have.property('saleId');
        // expect(instance.saleId).to.be(expectedValueLiteral);
      });

      it('should have the property protestLink (base name: "protest_link")', function() {
        // TODO: update the code to test the property protestLink
        expect(instance).to.have.property('protestLink');
        // expect(instance.protestLink).to.be(expectedValueLiteral);
      });

      it('should have the property amountFee (base name: "amount_fee")', function() {
        // TODO: update the code to test the property amountFee
        expect(instance).to.have.property('amountFee');
        // expect(instance.amountFee).to.be(expectedValueLiteral);
      });

    });
  });

}));
