/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParcelaExpressApi);
  }
}(this, function(expect, ParcelaExpressApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ParcelaExpressApi.EditSellerPartialDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EditSellerPartialDto', function() {
    it('should create an instance of EditSellerPartialDto', function() {
      // uncomment below and update the code to test EditSellerPartialDto
      //var instane = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be.a(ParcelaExpressApi.EditSellerPartialDto);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property document (base name: "document")', function() {
      // uncomment below and update the code to test the property document
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property state_registration (base name: "state_registration")', function() {
      // uncomment below and update the code to test the property state_registration
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property settlement_type (base name: "settlement_type")', function() {
      // uncomment below and update the code to test the property settlement_type
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property bank_account (base name: "bank_account")', function() {
      // uncomment below and update the code to test the property bank_account
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property monthly_billing (base name: "monthly_billing")', function() {
      // uncomment below and update the code to test the property monthly_billing
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property covenant (base name: "covenant")', function() {
      // uncomment below and update the code to test the property covenant
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property is_split (base name: "is_split")', function() {
      // uncomment below and update the code to test the property is_split
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property absorb_costs (base name: "absorb_costs")', function() {
      // uncomment below and update the code to test the property absorb_costs
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property pix_pos (base name: "pix_pos")', function() {
      // uncomment below and update the code to test the property pix_pos
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property no_payment_methods (base name: "no_payment_methods")', function() {
      // uncomment below and update the code to test the property no_payment_methods
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property has_split_rules (base name: "has_split_rules")', function() {
      // uncomment below and update the code to test the property has_split_rules
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property protocol_customizations (base name: "protocol_customizations")', function() {
      // uncomment below and update the code to test the property protocol_customizations
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property custom_emails (base name: "custom_emails")', function() {
      // uncomment below and update the code to test the property custom_emails
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property report_customization (base name: "report_customization")', function() {
      // uncomment below and update the code to test the property report_customization
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property responsibles (base name: "responsibles")', function() {
      // uncomment below and update the code to test the property responsibles
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property cns (base name: "cns")', function() {
      // uncomment below and update the code to test the property cns
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property cnae (base name: "cnae")', function() {
      // uncomment below and update the code to test the property cnae
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property assignment (base name: "assignment")', function() {
      // uncomment below and update the code to test the property assignment
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property owner_name (base name: "owner_name")', function() {
      // uncomment below and update the code to test the property owner_name
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property owner_document (base name: "owner_document")', function() {
      // uncomment below and update the code to test the property owner_document
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property erp (base name: "erp")', function() {
      // uncomment below and update the code to test the property erp
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property document_ofac (base name: "document_ofac")', function() {
      // uncomment below and update the code to test the property document_ofac
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property document_onu (base name: "document_onu")', function() {
      // uncomment below and update the code to test the property document_onu
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property document_rf (base name: "document_rf")', function() {
      // uncomment below and update the code to test the property document_rf
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property created_at (base name: "created_at")', function() {
      // uncomment below and update the code to test the property created_at
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property merchant_id (base name: "merchant_id")', function() {
      // uncomment below and update the code to test the property merchant_id
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property sale_plan_id (base name: "sale_plan_id")', function() {
      // uncomment below and update the code to test the property sale_plan_id
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property billet_provider (base name: "billet_provider")', function() {
      // uncomment below and update the code to test the property billet_provider
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property pix_provider (base name: "pix_provider")', function() {
      // uncomment below and update the code to test the property pix_provider
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property owner_document_ofac (base name: "owner_document_ofac")', function() {
      // uncomment below and update the code to test the property owner_document_ofac
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property owner_document_onu (base name: "owner_document_onu")', function() {
      // uncomment below and update the code to test the property owner_document_onu
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property owner_document_pep (base name: "owner_document_pep")', function() {
      // uncomment below and update the code to test the property owner_document_pep
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property owner_document_ref (base name: "owner_document_ref")', function() {
      // uncomment below and update the code to test the property owner_document_ref
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property owner_birth (base name: "owner_birth")', function() {
      // uncomment below and update the code to test the property owner_birth
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property frontier (base name: "frontier")', function() {
      // uncomment below and update the code to test the property frontier
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property extract_name (base name: "extract_name")', function() {
      // uncomment below and update the code to test the property extract_name
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

    it('should have the property registered_omie (base name: "registered_omie")', function() {
      // uncomment below and update the code to test the property registered_omie
      //var instance = new ParcelaExpressApi.EditSellerPartialDto();
      //expect(instance).to.be();
    });

  });

}));
