/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParcelaExpressApi);
  }
}(this, function(expect, ParcelaExpressApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GetSellerAcceptedPaymentMethodsDto', function() {
      beforeEach(function() {
        instance = new ParcelaExpressApi.GetSellerAcceptedPaymentMethodsDto();
      });

      it('should create an instance of GetSellerAcceptedPaymentMethodsDto', function() {
        // TODO: update the code to test GetSellerAcceptedPaymentMethodsDto
        expect(instance).to.be.a(ParcelaExpressApi.GetSellerAcceptedPaymentMethodsDto);
      });

      it('should have the property billetPaymentIsPermitted (base name: "billet_payment_is_permitted")', function() {
        // TODO: update the code to test the property billetPaymentIsPermitted
        expect(instance).to.have.property('billetPaymentIsPermitted');
        // expect(instance.billetPaymentIsPermitted).to.be(expectedValueLiteral);
      });

      it('should have the property qrcodePaymentIsPermitted (base name: "qrcode_payment_is_permitted")', function() {
        // TODO: update the code to test the property qrcodePaymentIsPermitted
        expect(instance).to.have.property('qrcodePaymentIsPermitted');
        // expect(instance.qrcodePaymentIsPermitted).to.be(expectedValueLiteral);
      });

      it('should have the property cardPaymentIsPermitted (base name: "card_payment_is_permitted")', function() {
        // TODO: update the code to test the property cardPaymentIsPermitted
        expect(instance).to.have.property('cardPaymentIsPermitted');
        // expect(instance.cardPaymentIsPermitted).to.be(expectedValueLiteral);
      });

    });
  });

}));
