/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParcelaExpressApi);
  }
}(this, function(expect, ParcelaExpressApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ParcelaExpressApi.GetSalePlanDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetSalePlanDto', function() {
    it('should create an instance of GetSalePlanDto', function() {
      // uncomment below and update the code to test GetSalePlanDto
      //var instane = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be.a(ParcelaExpressApi.GetSalePlanDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be();
    });

    it('should have the property payment_types (base name: "payment_types")', function() {
      // uncomment below and update the code to test the property payment_types
      //var instance = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be();
    });

    it('should have the property merchant (base name: "merchant")', function() {
      // uncomment below and update the code to test the property merchant
      //var instance = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be();
    });

    it('should have the property acquirer (base name: "acquirer")', function() {
      // uncomment below and update the code to test the property acquirer
      //var instance = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be();
    });

    it('should have the property settlement_plan (base name: "settlement_plan")', function() {
      // uncomment below and update the code to test the property settlement_plan
      //var instance = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be();
    });

    it('should have the property cost_plan (base name: "cost_plan")', function() {
      // uncomment below and update the code to test the property cost_plan
      //var instance = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be();
    });

    it('should have the property payment_method (base name: "payment_method")', function() {
      // uncomment below and update the code to test the property payment_method
      //var instance = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be();
    });

    it('should have the property risk_value (base name: "risk_value")', function() {
      // uncomment below and update the code to test the property risk_value
      //var instance = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be();
    });

    it('should have the property inactive (base name: "inactive")', function() {
      // uncomment below and update the code to test the property inactive
      //var instance = new ParcelaExpressApi.GetSalePlanDto();
      //expect(instance).to.be();
    });

  });

}));
