/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParcelaExpressApi);
  }
}(this, function(expect, ParcelaExpressApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ParcelaExpressApi.SplitRulesDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SplitRulesDto', function() {
    it('should create an instance of SplitRulesDto', function() {
      // uncomment below and update the code to test SplitRulesDto
      //var instane = new ParcelaExpressApi.SplitRulesDto();
      //expect(instance).to.be.a(ParcelaExpressApi.SplitRulesDto);
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new ParcelaExpressApi.SplitRulesDto();
      //expect(instance).to.be();
    });

    it('should have the property main_seller_id (base name: "main_seller_id")', function() {
      // uncomment below and update the code to test the property main_seller_id
      //var instance = new ParcelaExpressApi.SplitRulesDto();
      //expect(instance).to.be();
    });

    it('should have the property main_seller_name (base name: "main_seller_name")', function() {
      // uncomment below and update the code to test the property main_seller_name
      //var instance = new ParcelaExpressApi.SplitRulesDto();
      //expect(instance).to.be();
    });

    it('should have the property main_seller_document (base name: "main_seller_document")', function() {
      // uncomment below and update the code to test the property main_seller_document
      //var instance = new ParcelaExpressApi.SplitRulesDto();
      //expect(instance).to.be();
    });

    it('should have the property main_seller_code (base name: "main_seller_code")', function() {
      // uncomment below and update the code to test the property main_seller_code
      //var instance = new ParcelaExpressApi.SplitRulesDto();
      //expect(instance).to.be();
    });

    it('should have the property main_sale_id (base name: "main_sale_id")', function() {
      // uncomment below and update the code to test the property main_sale_id
      //var instance = new ParcelaExpressApi.SplitRulesDto();
      //expect(instance).to.be();
    });

    it('should have the property splits (base name: "splits")', function() {
      // uncomment below and update the code to test the property splits
      //var instance = new ParcelaExpressApi.SplitRulesDto();
      //expect(instance).to.be();
    });

  });

}));
