/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParcelaExpressApi);
  }
}(this, function(expect, ParcelaExpressApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ParcelaExpressApi.PaymentsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentsApi', function() {
    describe('capturePayment', function() {
      it('should call capturePayment successfully', function(done) {
        //uncomment below and update the code to test capturePayment
        //instance.capturePayment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createPayment', function() {
      it('should call createPayment successfully', function(done) {
        //uncomment below and update the code to test createPayment
        //instance.createPayment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createPaymentV3', function() {
      it('should call createPaymentV3 successfully', function(done) {
        //uncomment below and update the code to test createPaymentV3
        //instance.createPaymentV3(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createPaymentWithSplit', function() {
      it('should call createPaymentWithSplit successfully', function(done) {
        //uncomment below and update the code to test createPaymentWithSplit
        //instance.createPaymentWithSplit(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createPaymentWithSplitInternal', function() {
      it('should call createPaymentWithSplitInternal successfully', function(done) {
        //uncomment below and update the code to test createPaymentWithSplitInternal
        //instance.createPaymentWithSplitInternal(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createPixPayment', function() {
      it('should call createPixPayment successfully', function(done) {
        //uncomment below and update the code to test createPixPayment
        //instance.createPixPayment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createPixPaymentInternalWithSplits', function() {
      it('should call createPixPaymentInternalWithSplits successfully', function(done) {
        //uncomment below and update the code to test createPixPaymentInternalWithSplits
        //instance.createPixPaymentInternalWithSplits(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createPixPaymentWithSplits', function() {
      it('should call createPixPaymentWithSplits successfully', function(done) {
        //uncomment below and update the code to test createPixPaymentWithSplits
        //instance.createPixPaymentWithSplits(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentDetails', function() {
      it('should call paymentDetails successfully', function(done) {
        //uncomment below and update the code to test paymentDetails
        //instance.paymentDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentsControllerCancelPayment', function() {
      it('should call paymentsControllerCancelPayment successfully', function(done) {
        //uncomment below and update the code to test paymentsControllerCancelPayment
        //instance.paymentsControllerCancelPayment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
