/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ParcelaExpressApi);
  }
}(this, function(expect, ParcelaExpressApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ParcelaExpressApi.PosPaymentsApi();
  });

  describe('(package)', function() {
    describe('PosPaymentsApi', function() {
      describe('posControllerCancelPayment', function() {
        it('should call posControllerCancelPayment successfully', function(done) {
          // TODO: uncomment, update parameter values for posControllerCancelPayment call
          /*

          instance.posControllerCancelPayment(body, sellerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('posControllerPaymentsRequest', function() {
        it('should call posControllerPaymentsRequest successfully', function(done) {
          // TODO: uncomment, update parameter values for posControllerPaymentsRequest call and complete the assertions
          /*

          instance.posControllerPaymentsRequest(body, sellerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('posControllerV2PaymentsRequestWithSplit', function() {
        it('should call posControllerV2PaymentsRequestWithSplit successfully', function(done) {
          // TODO: uncomment, update parameter values for posControllerV2PaymentsRequestWithSplit call and complete the assertions
          /*

          instance.posControllerV2PaymentsRequestWithSplit(body, sellerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
