/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BarCodeDTO model module.
 * @module model/BarCodeDTO
 * @version 1.0
 */
class BarCodeDTO {
    /**
     * Constructs a new <code>BarCodeDTO</code>.
     * @alias module:model/BarCodeDTO
     * @param type {Number} 
     */
    constructor(type) { 
        
        BarCodeDTO.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>BarCodeDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BarCodeDTO} obj Optional instance to populate.
     * @return {module:model/BarCodeDTO} The populated <code>BarCodeDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BarCodeDTO();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
            if (data.hasOwnProperty('digitable')) {
                obj['digitable'] = ApiClient.convertToType(data['digitable'], 'String');
            }
            if (data.hasOwnProperty('barCode')) {
                obj['barCode'] = ApiClient.convertToType(data['barCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} type
 */
BarCodeDTO.prototype['type'] = undefined;

/**
 * @member {String} digitable
 */
BarCodeDTO.prototype['digitable'] = undefined;

/**
 * @member {String} barCode
 */
BarCodeDTO.prototype['barCode'] = undefined;






export default BarCodeDTO;

