/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreatePaymentLinkFromProtocolDto from './CreatePaymentLinkFromProtocolDto';

/**
 * The CreateProtocolDto model module.
 * @module model/CreateProtocolDto
 * @version 1.0
 */
class CreateProtocolDto {
    /**
     * Constructs a new <code>CreateProtocolDto</code>.
     * @alias module:model/CreateProtocolDto
     * @param number {Number} Número do protocolo
     * @param presenter_name {String} Nome do apresentante
     * @param has_email_notification {Boolean} Há notificação por email
     * @param has_payment_link {Boolean} Há link de pagamento
     * @param due_date {String} Data de vencimento
     * @param creation_date {String} Data de criação
     * @param seller_id {String} 
     */
    constructor(number, presenter_name, has_email_notification, has_payment_link, due_date, creation_date, seller_id) { 
        
        CreateProtocolDto.initialize(this, number, presenter_name, has_email_notification, has_payment_link, due_date, creation_date, seller_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, number, presenter_name, has_email_notification, has_payment_link, due_date, creation_date, seller_id) { 
        obj['number'] = number;
        obj['presenter_name'] = presenter_name;
        obj['has_email_notification'] = has_email_notification;
        obj['has_payment_link'] = has_payment_link;
        obj['due_date'] = due_date;
        obj['creation_date'] = creation_date;
        obj['seller_id'] = seller_id;
    }

    /**
     * Constructs a <code>CreateProtocolDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateProtocolDto} obj Optional instance to populate.
     * @return {module:model/CreateProtocolDto} The populated <code>CreateProtocolDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateProtocolDto();

            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('presenter_name')) {
                obj['presenter_name'] = ApiClient.convertToType(data['presenter_name'], 'String');
            }
            if (data.hasOwnProperty('value_cents')) {
                obj['value_cents'] = ApiClient.convertToType(data['value_cents'], 'Number');
            }
            if (data.hasOwnProperty('has_email_notification')) {
                obj['has_email_notification'] = ApiClient.convertToType(data['has_email_notification'], 'Boolean');
            }
            if (data.hasOwnProperty('payer_email')) {
                obj['payer_email'] = ApiClient.convertToType(data['payer_email'], 'String');
            }
            if (data.hasOwnProperty('email_content')) {
                obj['email_content'] = ApiClient.convertToType(data['email_content'], 'String');
            }
            if (data.hasOwnProperty('has_payment_link')) {
                obj['has_payment_link'] = ApiClient.convertToType(data['has_payment_link'], 'Boolean');
            }
            if (data.hasOwnProperty('payment_link')) {
                obj['payment_link'] = ApiClient.convertToType(data['payment_link'], CreatePaymentLinkFromProtocolDto);
            }
            if (data.hasOwnProperty('due_date')) {
                obj['due_date'] = ApiClient.convertToType(data['due_date'], 'String');
            }
            if (data.hasOwnProperty('creation_date')) {
                obj['creation_date'] = ApiClient.convertToType(data['creation_date'], 'String');
            }
            if (data.hasOwnProperty('seller_id')) {
                obj['seller_id'] = ApiClient.convertToType(data['seller_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Número do protocolo
 * @member {Number} number
 */
CreateProtocolDto.prototype['number'] = undefined;

/**
 * Nome do apresentante
 * @member {String} presenter_name
 */
CreateProtocolDto.prototype['presenter_name'] = undefined;

/**
 * Valor em centavos
 * @member {Number} value_cents
 */
CreateProtocolDto.prototype['value_cents'] = undefined;

/**
 * Há notificação por email
 * @member {Boolean} has_email_notification
 */
CreateProtocolDto.prototype['has_email_notification'] = undefined;

/**
 * Email do pagador
 * @member {String} payer_email
 */
CreateProtocolDto.prototype['payer_email'] = undefined;

/**
 * Conteúdo do email
 * @member {String} email_content
 */
CreateProtocolDto.prototype['email_content'] = undefined;

/**
 * Há link de pagamento
 * @member {Boolean} has_payment_link
 */
CreateProtocolDto.prototype['has_payment_link'] = undefined;

/**
 * Link de pagamento
 * @member {module:model/CreatePaymentLinkFromProtocolDto} payment_link
 */
CreateProtocolDto.prototype['payment_link'] = undefined;

/**
 * Data de vencimento
 * @member {String} due_date
 */
CreateProtocolDto.prototype['due_date'] = undefined;

/**
 * Data de criação
 * @member {String} creation_date
 */
CreateProtocolDto.prototype['creation_date'] = undefined;

/**
 * @member {String} seller_id
 */
CreateProtocolDto.prototype['seller_id'] = undefined;






export default CreateProtocolDto;

