/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateAttachmentDto from './CreateAttachmentDto';

/**
 * The CreateSellerRiskDto model module.
 * @module model/CreateSellerRiskDto
 * @version 1.0
 */
class CreateSellerRiskDto {
    /**
     * Constructs a new <code>CreateSellerRiskDto</code>.
     * @alias module:model/CreateSellerRiskDto
     * @param seller_id {String} 
     * @param classification {module:model/CreateSellerRiskDto.ClassificationEnum} 
     * @param negative_media {Boolean} 
     * @param lawsuits {Boolean} 
     * @param attachments {Array.<module:model/CreateAttachmentDto>} 
     * @param note {String} 
     */
    constructor(seller_id, classification, negative_media, lawsuits, attachments, note) { 
        
        CreateSellerRiskDto.initialize(this, seller_id, classification, negative_media, lawsuits, attachments, note);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, seller_id, classification, negative_media, lawsuits, attachments, note) { 
        obj['seller_id'] = seller_id;
        obj['classification'] = classification;
        obj['negative_media'] = negative_media;
        obj['lawsuits'] = lawsuits;
        obj['attachments'] = attachments;
        obj['note'] = note;
    }

    /**
     * Constructs a <code>CreateSellerRiskDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateSellerRiskDto} obj Optional instance to populate.
     * @return {module:model/CreateSellerRiskDto} The populated <code>CreateSellerRiskDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateSellerRiskDto();

            if (data.hasOwnProperty('seller_id')) {
                obj['seller_id'] = ApiClient.convertToType(data['seller_id'], 'String');
            }
            if (data.hasOwnProperty('classification')) {
                obj['classification'] = ApiClient.convertToType(data['classification'], 'String');
            }
            if (data.hasOwnProperty('negative_media')) {
                obj['negative_media'] = ApiClient.convertToType(data['negative_media'], 'Boolean');
            }
            if (data.hasOwnProperty('lawsuits')) {
                obj['lawsuits'] = ApiClient.convertToType(data['lawsuits'], 'Boolean');
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [CreateAttachmentDto]);
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} seller_id
 */
CreateSellerRiskDto.prototype['seller_id'] = undefined;

/**
 * @member {module:model/CreateSellerRiskDto.ClassificationEnum} classification
 */
CreateSellerRiskDto.prototype['classification'] = undefined;

/**
 * @member {Boolean} negative_media
 */
CreateSellerRiskDto.prototype['negative_media'] = undefined;

/**
 * @member {Boolean} lawsuits
 */
CreateSellerRiskDto.prototype['lawsuits'] = undefined;

/**
 * @member {Array.<module:model/CreateAttachmentDto>} attachments
 */
CreateSellerRiskDto.prototype['attachments'] = undefined;

/**
 * @member {String} note
 */
CreateSellerRiskDto.prototype['note'] = undefined;





/**
 * Allowed values for the <code>classification</code> property.
 * @enum {String}
 * @readonly
 */
CreateSellerRiskDto['ClassificationEnum'] = {

    /**
     * value: "lower"
     * @const
     */
    "lower": "lower",

    /**
     * value: "medium"
     * @const
     */
    "medium": "medium",

    /**
     * value: "high"
     * @const
     */
    "high": "high"
};



export default CreateSellerRiskDto;

