/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateDebitAddressDTO model module.
 * @module model/CreateDebitAddressDTO
 * @version 1.0
 */
class CreateDebitAddressDTO {
    /**
     * Constructs a new <code>CreateDebitAddressDTO</code>.
     * @alias module:model/CreateDebitAddressDTO
     * @param city {String} 
     * @param country {String} 
     * @param house_number_or_name {String} 
     * @param postal_code {String} 
     * @param street {String} 
     * @param state {String} 
     */
    constructor(city, country, house_number_or_name, postal_code, street, state) { 
        
        CreateDebitAddressDTO.initialize(this, city, country, house_number_or_name, postal_code, street, state);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, city, country, house_number_or_name, postal_code, street, state) { 
        obj['city'] = city;
        obj['country'] = country;
        obj['house_number_or_name'] = house_number_or_name;
        obj['postal_code'] = postal_code;
        obj['street'] = street;
        obj['state'] = state;
    }

    /**
     * Constructs a <code>CreateDebitAddressDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateDebitAddressDTO} obj Optional instance to populate.
     * @return {module:model/CreateDebitAddressDTO} The populated <code>CreateDebitAddressDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateDebitAddressDTO();

            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('house_number_or_name')) {
                obj['house_number_or_name'] = ApiClient.convertToType(data['house_number_or_name'], 'String');
            }
            if (data.hasOwnProperty('postal_code')) {
                obj['postal_code'] = ApiClient.convertToType(data['postal_code'], 'String');
            }
            if (data.hasOwnProperty('street')) {
                obj['street'] = ApiClient.convertToType(data['street'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} city
 */
CreateDebitAddressDTO.prototype['city'] = undefined;

/**
 * @member {String} country
 */
CreateDebitAddressDTO.prototype['country'] = undefined;

/**
 * @member {String} house_number_or_name
 */
CreateDebitAddressDTO.prototype['house_number_or_name'] = undefined;

/**
 * @member {String} postal_code
 */
CreateDebitAddressDTO.prototype['postal_code'] = undefined;

/**
 * @member {String} street
 */
CreateDebitAddressDTO.prototype['street'] = undefined;

/**
 * @member {String} state
 */
CreateDebitAddressDTO.prototype['state'] = undefined;






export default CreateDebitAddressDTO;

