/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateMerchantPermissionDto model module.
 * @module model/CreateMerchantPermissionDto
 * @version 1.0
 */
class CreateMerchantPermissionDto {
    /**
     * Constructs a new <code>CreateMerchantPermissionDto</code>.
     * @alias module:model/CreateMerchantPermissionDto
     * @param denied_fields {Array.<String>} 
     */
    constructor(denied_fields) { 
        
        CreateMerchantPermissionDto.initialize(this, denied_fields);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, denied_fields) { 
        obj['denied_fields'] = denied_fields;
    }

    /**
     * Constructs a <code>CreateMerchantPermissionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateMerchantPermissionDto} obj Optional instance to populate.
     * @return {module:model/CreateMerchantPermissionDto} The populated <code>CreateMerchantPermissionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateMerchantPermissionDto();

            if (data.hasOwnProperty('denied_fields')) {
                obj['denied_fields'] = ApiClient.convertToType(data['denied_fields'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} denied_fields
 */
CreateMerchantPermissionDto.prototype['denied_fields'] = undefined;






export default CreateMerchantPermissionDto;

