/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateAttachmentDto model module.
 * @module model/CreateAttachmentDto
 * @version 1.0
 */
class CreateAttachmentDto {
    /**
     * Constructs a new <code>CreateAttachmentDto</code>.
     * @alias module:model/CreateAttachmentDto
     * @param name {String} 
     * @param extension {module:model/CreateAttachmentDto.ExtensionEnum} 
     * @param data {String} 
     * @param size {Number} 
     */
    constructor(name, extension, data, size) { 
        
        CreateAttachmentDto.initialize(this, name, extension, data, size);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, extension, data, size) { 
        obj['name'] = name;
        obj['extension'] = extension;
        obj['data'] = data;
        obj['size'] = size;
    }

    /**
     * Constructs a <code>CreateAttachmentDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateAttachmentDto} obj Optional instance to populate.
     * @return {module:model/CreateAttachmentDto} The populated <code>CreateAttachmentDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateAttachmentDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('extension')) {
                obj['extension'] = ApiClient.convertToType(data['extension'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
CreateAttachmentDto.prototype['name'] = undefined;

/**
 * @member {module:model/CreateAttachmentDto.ExtensionEnum} extension
 */
CreateAttachmentDto.prototype['extension'] = undefined;

/**
 * @member {String} data
 */
CreateAttachmentDto.prototype['data'] = undefined;

/**
 * @member {Number} size
 */
CreateAttachmentDto.prototype['size'] = undefined;





/**
 * Allowed values for the <code>extension</code> property.
 * @enum {String}
 * @readonly
 */
CreateAttachmentDto['ExtensionEnum'] = {

    /**
     * value: "png"
     * @const
     */
    "png": "png",

    /**
     * value: "jpeg"
     * @const
     */
    "jpeg": "jpeg",

    /**
     * value: "jpg"
     * @const
     */
    "jpg": "jpg",

    /**
     * value: "pdf"
     * @const
     */
    "pdf": "pdf",

    /**
     * value: "doc"
     * @const
     */
    "doc": "doc",

    /**
     * value: "docx"
     * @const
     */
    "docx": "docx",

    /**
     * value: "xls"
     * @const
     */
    "xls": "xls",

    /**
     * value: "xlsx"
     * @const
     */
    "xlsx": "xlsx",

    /**
     * value: "rar"
     * @const
     */
    "rar": "rar",

    /**
     * value: "zip"
     * @const
     */
    "zip": "zip",

    /**
     * value: "csv"
     * @const
     */
    "csv": "csv"
};



export default CreateAttachmentDto;

