/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CardDTO from './CardDTO';
import CustomerDTO from './CustomerDTO';
import InstallmentPlanDTO from './InstallmentPlanDTO';

/**
 * The CreatePaymentDto model module.
 * @module model/CreatePaymentDto
 * @version 1.0
 */
class CreatePaymentDto {
    /**
     * Constructs a new <code>CreatePaymentDto</code>.
     * @alias module:model/CreatePaymentDto
     * @param amount_cents {Number} Valor em centavos
     * @param description {String} Descrição
     * @param card_attributes {module:model/CardDTO} Informações do cartão
     * @param installment_plan {module:model/InstallmentPlanDTO} Parcelamento
     * @param customer {module:model/CustomerDTO} Cliente
     */
    constructor(amount_cents, description, card_attributes, installment_plan, customer) { 
        
        CreatePaymentDto.initialize(this, amount_cents, description, card_attributes, installment_plan, customer);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount_cents, description, card_attributes, installment_plan, customer) { 
        obj['amount_cents'] = amount_cents;
        obj['description'] = description;
        obj['card_attributes'] = card_attributes;
        obj['installment_plan'] = installment_plan;
        obj['customer'] = customer;
    }

    /**
     * Constructs a <code>CreatePaymentDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePaymentDto} obj Optional instance to populate.
     * @return {module:model/CreatePaymentDto} The populated <code>CreatePaymentDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePaymentDto();

            if (data.hasOwnProperty('amount_cents')) {
                obj['amount_cents'] = ApiClient.convertToType(data['amount_cents'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('card_attributes')) {
                obj['card_attributes'] = ApiClient.convertToType(data['card_attributes'], CardDTO);
            }
            if (data.hasOwnProperty('installment_plan')) {
                obj['installment_plan'] = ApiClient.convertToType(data['installment_plan'], InstallmentPlanDTO);
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = ApiClient.convertToType(data['customer'], CustomerDTO);
            }
            if (data.hasOwnProperty('pre_capture')) {
                obj['pre_capture'] = ApiClient.convertToType(data['pre_capture'], 'Boolean');
            }
            if (data.hasOwnProperty('form_payment')) {
                obj['form_payment'] = ApiClient.convertToType(data['form_payment'], 'String');
            }
            if (data.hasOwnProperty('success_return_url')) {
                obj['success_return_url'] = ApiClient.convertToType(data['success_return_url'], 'String');
            }
            if (data.hasOwnProperty('error_return_url')) {
                obj['error_return_url'] = ApiClient.convertToType(data['error_return_url'], 'String');
            }
            if (data.hasOwnProperty('recurrence')) {
                obj['recurrence'] = ApiClient.convertToType(data['recurrence'], 'Boolean');
            }
            if (data.hasOwnProperty('recurrence_day')) {
                obj['recurrence_day'] = ApiClient.convertToType(data['recurrence_day'], 'Number');
            }
            if (data.hasOwnProperty('sale_id')) {
                obj['sale_id'] = ApiClient.convertToType(data['sale_id'], 'String');
            }
            if (data.hasOwnProperty('protest_link')) {
                obj['protest_link'] = ApiClient.convertToType(data['protest_link'], 'Boolean');
            }
            if (data.hasOwnProperty('amount_fee')) {
                obj['amount_fee'] = ApiClient.convertToType(data['amount_fee'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Valor em centavos
 * @member {Number} amount_cents
 */
CreatePaymentDto.prototype['amount_cents'] = undefined;

/**
 * Descrição
 * @member {String} description
 */
CreatePaymentDto.prototype['description'] = undefined;

/**
 * Informações do cartão
 * @member {module:model/CardDTO} card_attributes
 */
CreatePaymentDto.prototype['card_attributes'] = undefined;

/**
 * Parcelamento
 * @member {module:model/InstallmentPlanDTO} installment_plan
 */
CreatePaymentDto.prototype['installment_plan'] = undefined;

/**
 * Cliente
 * @member {module:model/CustomerDTO} customer
 */
CreatePaymentDto.prototype['customer'] = undefined;

/**
 * Pré captura
 * @member {Boolean} pre_capture
 */
CreatePaymentDto.prototype['pre_capture'] = undefined;

/**
 * Forma de pagamento
 * @member {module:model/CreatePaymentDto.FormPaymentEnum} form_payment
 */
CreatePaymentDto.prototype['form_payment'] = undefined;

/**
 * Url de redirecionamento de sucesso (exclusivo 3DS)
 * @member {String} success_return_url
 */
CreatePaymentDto.prototype['success_return_url'] = undefined;

/**
 * Url de redirecionamento de erro (exclusivo 3DS)
 * @member {String} error_return_url
 */
CreatePaymentDto.prototype['error_return_url'] = undefined;

/**
 * Assinatura
 * @member {Boolean} recurrence
 */
CreatePaymentDto.prototype['recurrence'] = undefined;

/**
 * Data de cobrança assinatura
 * @member {Number} recurrence_day
 */
CreatePaymentDto.prototype['recurrence_day'] = undefined;

/**
 * @member {String} sale_id
 */
CreatePaymentDto.prototype['sale_id'] = undefined;

/**
 * @member {Boolean} protest_link
 */
CreatePaymentDto.prototype['protest_link'] = undefined;

/**
 * @member {Number} amount_fee
 */
CreatePaymentDto.prototype['amount_fee'] = undefined;





/**
 * Allowed values for the <code>form_payment</code> property.
 * @enum {String}
 * @readonly
 */
CreatePaymentDto['FormPaymentEnum'] = {

    /**
     * value: "credit"
     * @const
     */
    "credit": "credit",

    /**
     * value: "debit"
     * @const
     */
    "debit": "debit",

    /**
     * value: "billet"
     * @const
     */
    "billet": "billet",

    /**
     * value: "pix"
     * @const
     */
    "pix": "pix",

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "pix_pos"
     * @const
     */
    "pix_pos": "pix_pos"
};



export default CreatePaymentDto;

