/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateSaleDto model module.
 * @module model/CreateSaleDto
 * @version 1.0
 */
class CreateSaleDto {
    /**
     * Constructs a new <code>CreateSaleDto</code>.
     * @alias module:model/CreateSaleDto
     * @param description {String} Descricão
     * @param original_amount {Number} Valor original
     * @param type {module:model/CreateSaleDto.TypeEnum} Tipo de venda
     * @param status {module:model/CreateSaleDto.StatusEnum} 
     * @param sale_plan_id {String} 
     * @param payment_type_id {String} 
     */
    constructor(description, original_amount, type, status, sale_plan_id, payment_type_id) { 
        
        CreateSaleDto.initialize(this, description, original_amount, type, status, sale_plan_id, payment_type_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, description, original_amount, type, status, sale_plan_id, payment_type_id) { 
        obj['description'] = description;
        obj['original_amount'] = original_amount;
        obj['type'] = type;
        obj['status'] = status;
        obj['sale_plan_id'] = sale_plan_id;
        obj['payment_type_id'] = payment_type_id;
    }

    /**
     * Constructs a <code>CreateSaleDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateSaleDto} obj Optional instance to populate.
     * @return {module:model/CreateSaleDto} The populated <code>CreateSaleDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateSaleDto();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('original_amount')) {
                obj['original_amount'] = ApiClient.convertToType(data['original_amount'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('acquirer_reference')) {
                obj['acquirer_reference'] = ApiClient.convertToType(data['acquirer_reference'], 'String');
            }
            if (data.hasOwnProperty('form_payment')) {
                obj['form_payment'] = ApiClient.convertToType(data['form_payment'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('terminal_id')) {
                obj['terminal_id'] = ApiClient.convertToType(data['terminal_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('sale_plan_id')) {
                obj['sale_plan_id'] = ApiClient.convertToType(data['sale_plan_id'], 'String');
            }
            if (data.hasOwnProperty('payment_type_id')) {
                obj['payment_type_id'] = ApiClient.convertToType(data['payment_type_id'], 'String');
            }
            if (data.hasOwnProperty('payer_id')) {
                obj['payer_id'] = ApiClient.convertToType(data['payer_id'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Descricão
 * @member {String} description
 */
CreateSaleDto.prototype['description'] = undefined;

/**
 * Valor original
 * @member {Number} original_amount
 */
CreateSaleDto.prototype['original_amount'] = undefined;

/**
 * Valor
 * @member {Number} amount
 */
CreateSaleDto.prototype['amount'] = undefined;

/**
 * Id na adquirente
 * @member {String} acquirer_reference
 */
CreateSaleDto.prototype['acquirer_reference'] = undefined;

/**
 * Forma de pagamento
 * @member {String} form_payment
 */
CreateSaleDto.prototype['form_payment'] = undefined;

/**
 * Tipo de venda
 * @member {module:model/CreateSaleDto.TypeEnum} type
 */
CreateSaleDto.prototype['type'] = undefined;

/**
 * Id da máquina de pagamento
 * @member {String} terminal_id
 */
CreateSaleDto.prototype['terminal_id'] = undefined;

/**
 * @member {module:model/CreateSaleDto.StatusEnum} status
 */
CreateSaleDto.prototype['status'] = undefined;

/**
 * @member {String} sale_plan_id
 */
CreateSaleDto.prototype['sale_plan_id'] = undefined;

/**
 * @member {String} payment_type_id
 */
CreateSaleDto.prototype['payment_type_id'] = undefined;

/**
 * @member {String} payer_id
 */
CreateSaleDto.prototype['payer_id'] = undefined;

/**
 * @member {String} metadata
 */
CreateSaleDto.prototype['metadata'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CreateSaleDto['TypeEnum'] = {

    /**
     * value: "boleto"
     * @const
     */
    "boleto": "boleto",

    /**
     * value: "pos"
     * @const
     */
    "pos": "pos",

    /**
     * value: "payment_link"
     * @const
     */
    "payment_link": "payment_link",

    /**
     * value: "protest_link"
     * @const
     */
    "protest_link": "protest_link",

    /**
     * value: "online"
     * @const
     */
    "online": "online",

    /**
     * value: "auto_generate_payment_link"
     * @const
     */
    "auto_generate_payment_link": "auto_generate_payment_link",

    /**
     * value: "auto_generate_protest_link"
     * @const
     */
    "auto_generate_protest_link": "auto_generate_protest_link",

    /**
     * value: "billet_code"
     * @const
     */
    "billet_code": "billet_code",

    /**
     * value: "bill_payment"
     * @const
     */
    "bill_payment": "bill_payment"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
CreateSaleDto['StatusEnum'] = {

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "pending_capture"
     * @const
     */
    "pending_capture": "pending_capture",

    /**
     * value: "in_progress_capture"
     * @const
     */
    "in_progress_capture": "in_progress_capture",

    /**
     * value: "succeeded"
     * @const
     */
    "succeeded": "succeeded",

    /**
     * value: "canceled"
     * @const
     */
    "canceled": "canceled",

    /**
     * value: "pending_cancel"
     * @const
     */
    "pending_cancel": "pending_cancel",

    /**
     * value: "abort"
     * @const
     */
    "abort": "abort",

    /**
     * value: "failed"
     * @const
     */
    "failed": "failed",

    /**
     * value: "waiting_confirmation"
     * @const
     */
    "waiting_confirmation": "waiting_confirmation",

    /**
     * value: "expired"
     * @const
     */
    "expired": "expired",

    /**
     * value: "waiting_cashIn"
     * @const
     */
    "waiting_cashIn": "waiting_cashIn"
};



export default CreateSaleDto;

