/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Splits} from './Splits';

/**
 * The CreateMetadataDto model module.
 * @module model/CreateMetadataDto
 * @version 1.0
 */
export class CreateMetadataDto {
  /**
   * Constructs a new <code>CreateMetadataDto</code>.
   * @alias module:model/CreateMetadataDto
   * @class
   * @param acquirerReference {String} 
   */
  constructor(acquirerReference) {
    this.acquirerReference = acquirerReference;
  }

  /**
   * Constructs a <code>CreateMetadataDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateMetadataDto} obj Optional instance to populate.
   * @return {module:model/CreateMetadataDto} The populated <code>CreateMetadataDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateMetadataDto();
      if (data.hasOwnProperty('acquirerReference'))
        obj.acquirerReference = ApiClient.convertToType(data['acquirerReference'], 'String');
      if (data.hasOwnProperty('originalReference'))
        obj.originalReference = ApiClient.convertToType(data['originalReference'], 'String');
      if (data.hasOwnProperty('split_rules'))
        obj.splitRules = ApiClient.convertToType(data['split_rules'], [Splits]);
      if (data.hasOwnProperty('split_rules_id'))
        obj.splitRulesId = ApiClient.convertToType(data['split_rules_id'], 'String');
      if (data.hasOwnProperty('has_split_rules'))
        obj.hasSplitRules = ApiClient.convertToType(data['has_split_rules'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} acquirerReference
 */
CreateMetadataDto.prototype.acquirerReference = undefined;

/**
 * @member {String} originalReference
 */
CreateMetadataDto.prototype.originalReference = undefined;

/**
 * @member {Array.<module:model/Splits>} splitRules
 */
CreateMetadataDto.prototype.splitRules = undefined;

/**
 * @member {String} splitRulesId
 */
CreateMetadataDto.prototype.splitRulesId = undefined;

/**
 * @member {Boolean} hasSplitRules
 */
CreateMetadataDto.prototype.hasSplitRules = undefined;

