/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CreateProtestLinkPayerDto} from './CreateProtestLinkPayerDto';

/**
 * The CreateProtestLinkDto model module.
 * @module model/CreateProtestLinkDto
 * @version 1.0
 */
export class CreateProtestLinkDto {
  /**
   * Constructs a new <code>CreateProtestLinkDto</code>.
   * @alias module:model/CreateProtestLinkDto
   * @class
   * @param amount {Number} 
   * @param fee {Number} 
   * @param description {String} 
   * @param sellerId {String} 
   * @param payer {module:model/CreateProtestLinkPayerDto} 
   * @param paymentMethods {Array.<String>} 
   */
  constructor(amount, fee, description, sellerId, payer, paymentMethods) {
    this.amount = amount;
    this.fee = fee;
    this.description = description;
    this.sellerId = sellerId;
    this.payer = payer;
    this.paymentMethods = paymentMethods;
  }

  /**
   * Constructs a <code>CreateProtestLinkDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateProtestLinkDto} obj Optional instance to populate.
   * @return {module:model/CreateProtestLinkDto} The populated <code>CreateProtestLinkDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateProtestLinkDto();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('fee'))
        obj.fee = ApiClient.convertToType(data['fee'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('expires_in'))
        obj.expiresIn = ApiClient.convertToType(data['expires_in'], 'String');
      if (data.hasOwnProperty('seller_id'))
        obj.sellerId = ApiClient.convertToType(data['seller_id'], 'String');
      if (data.hasOwnProperty('payer'))
        obj.payer = CreateProtestLinkPayerDto.constructFromObject(data['payer']);
      if (data.hasOwnProperty('payment_methods'))
        obj.paymentMethods = ApiClient.convertToType(data['payment_methods'], ['String']);
      if (data.hasOwnProperty('pre_capture'))
        obj.preCapture = ApiClient.convertToType(data['pre_capture'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} amount
 */
CreateProtestLinkDto.prototype.amount = undefined;

/**
 * @member {Number} fee
 */
CreateProtestLinkDto.prototype.fee = undefined;

/**
 * @member {String} description
 */
CreateProtestLinkDto.prototype.description = undefined;

/**
 * @member {String} expiresIn
 */
CreateProtestLinkDto.prototype.expiresIn = undefined;

/**
 * @member {String} sellerId
 */
CreateProtestLinkDto.prototype.sellerId = undefined;

/**
 * @member {module:model/CreateProtestLinkPayerDto} payer
 */
CreateProtestLinkDto.prototype.payer = undefined;

/**
 * @member {Array.<String>} paymentMethods
 */
CreateProtestLinkDto.prototype.paymentMethods = undefined;

/**
 * @member {Boolean} preCapture
 */
CreateProtestLinkDto.prototype.preCapture = undefined;

