/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateExportSellersListDto model module.
 * @module model/CreateExportSellersListDto
 * @version 1.0
 */
class CreateExportSellersListDto {
    /**
     * Constructs a new <code>CreateExportSellersListDto</code>.
     * @alias module:model/CreateExportSellersListDto
     */
    constructor() { 
        
        CreateExportSellersListDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateExportSellersListDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateExportSellersListDto} obj Optional instance to populate.
     * @return {module:model/CreateExportSellersListDto} The populated <code>CreateExportSellersListDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateExportSellersListDto();

            if (data.hasOwnProperty('updated_day')) {
                obj['updated_day'] = ApiClient.convertToType(data['updated_day'], 'Boolean');
            }
            if (data.hasOwnProperty('created_by_user_name')) {
                obj['created_by_user_name'] = ApiClient.convertToType(data['created_by_user_name'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('document')) {
                obj['document'] = ApiClient.convertToType(data['document'], 'String');
            }
            if (data.hasOwnProperty('cns')) {
                obj['cns'] = ApiClient.convertToType(data['cns'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], ['String']);
            }
            if (data.hasOwnProperty('extension')) {
                obj['extension'] = ApiClient.convertToType(data['extension'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Dia da atualização
 * @member {Boolean} updated_day
 */
CreateExportSellersListDto.prototype['updated_day'] = undefined;

/**
 * Usuário logado
 * @member {String} created_by_user_name
 */
CreateExportSellersListDto.prototype['created_by_user_name'] = undefined;

/**
 * @member {String} name
 */
CreateExportSellersListDto.prototype['name'] = undefined;

/**
 * @member {String} document
 */
CreateExportSellersListDto.prototype['document'] = undefined;

/**
 * @member {String} cns
 */
CreateExportSellersListDto.prototype['cns'] = undefined;

/**
 * @member {String} code
 */
CreateExportSellersListDto.prototype['code'] = undefined;

/**
 * @member {Array.<module:model/CreateExportSellersListDto.StatusEnum>} status
 */
CreateExportSellersListDto.prototype['status'] = undefined;

/**
 * @member {module:model/CreateExportSellersListDto.ExtensionEnum} extension
 */
CreateExportSellersListDto.prototype['extension'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
CreateExportSellersListDto['StatusEnum'] = {

    /**
     * value: "activated"
     * @const
     */
    "activated": "activated",

    /**
     * value: "inactive"
     * @const
     */
    "inactive": "inactive",

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "activation_sent"
     * @const
     */
    "activation_sent": "activation_sent"
};


/**
 * Allowed values for the <code>extension</code> property.
 * @enum {String}
 * @readonly
 */
CreateExportSellersListDto['ExtensionEnum'] = {

    /**
     * value: "xls"
     * @const
     */
    "xls": "xls",

    /**
     * value: "csv"
     * @const
     */
    "csv": "csv",

    /**
     * value: "json"
     * @const
     */
    "json": "json",

    /**
     * value: "pdf"
     * @const
     */
    "pdf": "pdf"
};



export default CreateExportSellersListDto;

