/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CardDTO from './CardDTO';
import CreateSplitRulesDto from './CreateSplitRulesDto';
import CustomerDTO from './CustomerDTO';
import InstallmentPlanDTO from './InstallmentPlanDTO';

/**
 * The CreatePaymentWithSplitDto model module.
 * @module model/CreatePaymentWithSplitDto
 * @version 1.0
 */
class CreatePaymentWithSplitDto {
    /**
     * Constructs a new <code>CreatePaymentWithSplitDto</code>.
     * @alias module:model/CreatePaymentWithSplitDto
     * @param amount_cents {Number} Valor em centavos
     * @param description {String} Descrição
     * @param card_attributes {module:model/CardDTO} 
     * @param installment_plan {module:model/InstallmentPlanDTO} Parcelamento
     * @param customer {module:model/CustomerDTO} Cliente
     */
    constructor(amount_cents, description, card_attributes, installment_plan, customer) { 
        
        CreatePaymentWithSplitDto.initialize(this, amount_cents, description, card_attributes, installment_plan, customer);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount_cents, description, card_attributes, installment_plan, customer) { 
        obj['amount_cents'] = amount_cents;
        obj['description'] = description;
        obj['card_attributes'] = card_attributes;
        obj['installment_plan'] = installment_plan;
        obj['customer'] = customer;
    }

    /**
     * Constructs a <code>CreatePaymentWithSplitDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePaymentWithSplitDto} obj Optional instance to populate.
     * @return {module:model/CreatePaymentWithSplitDto} The populated <code>CreatePaymentWithSplitDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePaymentWithSplitDto();

            if (data.hasOwnProperty('amount_cents')) {
                obj['amount_cents'] = ApiClient.convertToType(data['amount_cents'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('card_attributes')) {
                obj['card_attributes'] = ApiClient.convertToType(data['card_attributes'], CardDTO);
            }
            if (data.hasOwnProperty('installment_plan')) {
                obj['installment_plan'] = ApiClient.convertToType(data['installment_plan'], InstallmentPlanDTO);
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = ApiClient.convertToType(data['customer'], CustomerDTO);
            }
            if (data.hasOwnProperty('sale_id')) {
                obj['sale_id'] = ApiClient.convertToType(data['sale_id'], 'String');
            }
            if (data.hasOwnProperty('protest_link')) {
                obj['protest_link'] = ApiClient.convertToType(data['protest_link'], 'Boolean');
            }
            if (data.hasOwnProperty('amount_fee')) {
                obj['amount_fee'] = ApiClient.convertToType(data['amount_fee'], 'Number');
            }
            if (data.hasOwnProperty('pre_capture')) {
                obj['pre_capture'] = ApiClient.convertToType(data['pre_capture'], 'Boolean');
            }
            if (data.hasOwnProperty('form_payment')) {
                obj['form_payment'] = ApiClient.convertToType(data['form_payment'], 'String');
            }
            if (data.hasOwnProperty('success_return_url')) {
                obj['success_return_url'] = ApiClient.convertToType(data['success_return_url'], 'String');
            }
            if (data.hasOwnProperty('error_return_url')) {
                obj['error_return_url'] = ApiClient.convertToType(data['error_return_url'], 'String');
            }
            if (data.hasOwnProperty('has_split_rules')) {
                obj['has_split_rules'] = ApiClient.convertToType(data['has_split_rules'], 'Boolean');
            }
            if (data.hasOwnProperty('split_rules')) {
                obj['split_rules'] = ApiClient.convertToType(data['split_rules'], [CreateSplitRulesDto]);
            }
            if (data.hasOwnProperty('confirmation_required')) {
                obj['confirmation_required'] = ApiClient.convertToType(data['confirmation_required'], 'Boolean');
            }
            if (data.hasOwnProperty('extract_identification')) {
                obj['extract_identification'] = ApiClient.convertToType(data['extract_identification'], 'String');
            }
            if (data.hasOwnProperty('active_3ds')) {
                obj['active_3ds'] = ApiClient.convertToType(data['active_3ds'], 'Boolean');
            }
            if (data.hasOwnProperty('risk_custom_field')) {
                obj['risk_custom_field'] = ApiClient.convertToType(data['risk_custom_field'], 'String');
            }
            if (data.hasOwnProperty('service_id')) {
                obj['service_id'] = ApiClient.convertToType(data['service_id'], 'String');
            }
            if (data.hasOwnProperty('protocol')) {
                obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Valor em centavos
 * @member {Number} amount_cents
 */
CreatePaymentWithSplitDto.prototype['amount_cents'] = undefined;

/**
 * Descrição
 * @member {String} description
 */
CreatePaymentWithSplitDto.prototype['description'] = undefined;

/**
 * @member {module:model/CardDTO} card_attributes
 */
CreatePaymentWithSplitDto.prototype['card_attributes'] = undefined;

/**
 * Parcelamento
 * @member {module:model/InstallmentPlanDTO} installment_plan
 */
CreatePaymentWithSplitDto.prototype['installment_plan'] = undefined;

/**
 * Cliente
 * @member {module:model/CustomerDTO} customer
 */
CreatePaymentWithSplitDto.prototype['customer'] = undefined;

/**
 * Id da venda
 * @member {String} sale_id
 */
CreatePaymentWithSplitDto.prototype['sale_id'] = undefined;

/**
 * Criado via link de protesto
 * @member {Boolean} protest_link
 */
CreatePaymentWithSplitDto.prototype['protest_link'] = undefined;

/**
 * Valor da taxa
 * @member {Number} amount_fee
 */
CreatePaymentWithSplitDto.prototype['amount_fee'] = undefined;

/**
 * Pré captura
 * @member {Boolean} pre_capture
 */
CreatePaymentWithSplitDto.prototype['pre_capture'] = undefined;

/**
 * Forma de pagamento
 * @member {module:model/CreatePaymentWithSplitDto.FormPaymentEnum} form_payment
 */
CreatePaymentWithSplitDto.prototype['form_payment'] = undefined;

/**
 * Url de redirecionamento de sucesso (exclusivo 3DS)
 * @member {String} success_return_url
 */
CreatePaymentWithSplitDto.prototype['success_return_url'] = undefined;

/**
 * Url de redirecionamento de erro (exclusivo 3DS)
 * @member {String} error_return_url
 */
CreatePaymentWithSplitDto.prototype['error_return_url'] = undefined;

/**
 * Há Divisão de pagamento
 * @member {Boolean} has_split_rules
 */
CreatePaymentWithSplitDto.prototype['has_split_rules'] = undefined;

/**
 * Divisão de pagamento
 * @member {Array.<module:model/CreateSplitRulesDto>} split_rules
 */
CreatePaymentWithSplitDto.prototype['split_rules'] = undefined;

/**
 * Há confirmação de pagamento
 * @member {Boolean} confirmation_required
 */
CreatePaymentWithSplitDto.prototype['confirmation_required'] = undefined;

/**
 * Identificação do extrato. Recomenda-se usar até 22 caracteres, pois o banco pode excluir o excedente
 * @member {String} extract_identification
 */
CreatePaymentWithSplitDto.prototype['extract_identification'] = undefined;

/**
 * Ativar 3DS
 * @member {Boolean} active_3ds
 */
CreatePaymentWithSplitDto.prototype['active_3ds'] = undefined;

/**
 * Campo de risco customizável
 * @member {String} risk_custom_field
 */
CreatePaymentWithSplitDto.prototype['risk_custom_field'] = undefined;

/**
 * Identificador externo
 * @member {String} service_id
 */
CreatePaymentWithSplitDto.prototype['service_id'] = undefined;

/**
 * Número do protocolo
 * @member {String} protocol
 */
CreatePaymentWithSplitDto.prototype['protocol'] = undefined;





/**
 * Allowed values for the <code>form_payment</code> property.
 * @enum {String}
 * @readonly
 */
CreatePaymentWithSplitDto['FormPaymentEnum'] = {

    /**
     * value: "credit"
     * @const
     */
    "credit": "credit",

    /**
     * value: "debit"
     * @const
     */
    "debit": "debit",

    /**
     * value: "billet"
     * @const
     */
    "billet": "billet",

    /**
     * value: "pix"
     * @const
     */
    "pix": "pix",

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "pix_pos"
     * @const
     */
    "pix_pos": "pix_pos"
};



export default CreatePaymentWithSplitDto;

