/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateSellerFileExportRequestDto model module.
 * @module model/CreateSellerFileExportRequestDto
 * @version 1.0
 */
class CreateSellerFileExportRequestDto {
    /**
     * Constructs a new <code>CreateSellerFileExportRequestDto</code>.
     * @alias module:model/CreateSellerFileExportRequestDto
     * @param type {module:model/CreateSellerFileExportRequestDto.TypeEnum} 
     * @param extension {module:model/CreateSellerFileExportRequestDto.ExtensionEnum} 
     * @param start_date {String} 
     * @param end_date {String} 
     * @param querystring {String} 
     */
    constructor(type, extension, start_date, end_date, querystring) { 
        
        CreateSellerFileExportRequestDto.initialize(this, type, extension, start_date, end_date, querystring);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, extension, start_date, end_date, querystring) { 
        obj['type'] = type;
        obj['extension'] = extension;
        obj['start_date'] = start_date;
        obj['end_date'] = end_date;
        obj['querystring'] = querystring;
    }

    /**
     * Constructs a <code>CreateSellerFileExportRequestDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateSellerFileExportRequestDto} obj Optional instance to populate.
     * @return {module:model/CreateSellerFileExportRequestDto} The populated <code>CreateSellerFileExportRequestDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateSellerFileExportRequestDto();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('extension')) {
                obj['extension'] = ApiClient.convertToType(data['extension'], 'String');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'String');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'String');
            }
            if (data.hasOwnProperty('querystring')) {
                obj['querystring'] = ApiClient.convertToType(data['querystring'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CreateSellerFileExportRequestDto.TypeEnum} type
 */
CreateSellerFileExportRequestDto.prototype['type'] = undefined;

/**
 * @member {module:model/CreateSellerFileExportRequestDto.ExtensionEnum} extension
 */
CreateSellerFileExportRequestDto.prototype['extension'] = undefined;

/**
 * @member {String} start_date
 */
CreateSellerFileExportRequestDto.prototype['start_date'] = undefined;

/**
 * @member {String} end_date
 */
CreateSellerFileExportRequestDto.prototype['end_date'] = undefined;

/**
 * @member {String} querystring
 */
CreateSellerFileExportRequestDto.prototype['querystring'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CreateSellerFileExportRequestDto['TypeEnum'] = {

    /**
     * value: "sales"
     * @const
     */
    "sales": "sales",

    /**
     * value: "sales_concil"
     * @const
     */
    "sales_concil": "sales_concil",

    /**
     * value: "payments"
     * @const
     */
    "payments": "payments",

    /**
     * value: "settlement"
     * @const
     */
    "settlement": "settlement",

    /**
     * value: "settlement_transactions"
     * @const
     */
    "settlement_transactions": "settlement_transactions",

    /**
     * value: "settlements_batch_transactions"
     * @const
     */
    "settlements_batch_transactions": "settlements_batch_transactions",

    /**
     * value: "protocols"
     * @const
     */
    "protocols": "protocols",

    /**
     * value: "sales_history"
     * @const
     */
    "sales_history": "sales_history",

    /**
     * value: "sellers"
     * @const
     */
    "sellers": "sellers",

    /**
     * value: "sales_bill_payment"
     * @const
     */
    "sales_bill_payment": "sales_bill_payment"
};


/**
 * Allowed values for the <code>extension</code> property.
 * @enum {String}
 * @readonly
 */
CreateSellerFileExportRequestDto['ExtensionEnum'] = {

    /**
     * value: "xls"
     * @const
     */
    "xls": "xls",

    /**
     * value: "csv"
     * @const
     */
    "csv": "csv",

    /**
     * value: "json"
     * @const
     */
    "json": "json",

    /**
     * value: "pdf"
     * @const
     */
    "pdf": "pdf"
};



export default CreateSellerFileExportRequestDto;

