/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CreateDebitCustomerDTO} from './CreateDebitCustomerDTO';

/**
 * The CreateDebitPaymentDto model module.
 * @module model/CreateDebitPaymentDto
 * @version 1.0
 */
export class CreateDebitPaymentDto {
  /**
   * Constructs a new <code>CreateDebitPaymentDto</code>.
   * @alias module:model/CreateDebitPaymentDto
   * @class
   * @param amountCents {Number} 
   * @param description {String} 
   * @param customer {module:model/CreateDebitCustomerDTO} 
   * @param cardAttributes {Object} 
   */
  constructor(amountCents, description, customer, cardAttributes) {
    this.amountCents = amountCents;
    this.description = description;
    this.customer = customer;
    this.cardAttributes = cardAttributes;
  }

  /**
   * Constructs a <code>CreateDebitPaymentDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateDebitPaymentDto} obj Optional instance to populate.
   * @return {module:model/CreateDebitPaymentDto} The populated <code>CreateDebitPaymentDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateDebitPaymentDto();
      if (data.hasOwnProperty('amount_cents'))
        obj.amountCents = ApiClient.convertToType(data['amount_cents'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('customer'))
        obj.customer = CreateDebitCustomerDTO.constructFromObject(data['customer']);
      if (data.hasOwnProperty('card_attributes'))
        obj.cardAttributes = ApiClient.convertToType(data['card_attributes'], Object);
      if (data.hasOwnProperty('sale_id'))
        obj.saleId = ApiClient.convertToType(data['sale_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} amountCents
 */
CreateDebitPaymentDto.prototype.amountCents = undefined;

/**
 * @member {String} description
 */
CreateDebitPaymentDto.prototype.description = undefined;

/**
 * @member {module:model/CreateDebitCustomerDTO} customer
 */
CreateDebitPaymentDto.prototype.customer = undefined;

/**
 * @member {Object} cardAttributes
 */
CreateDebitPaymentDto.prototype.cardAttributes = undefined;

/**
 * @member {String} saleId
 */
CreateDebitPaymentDto.prototype.saleId = undefined;

