/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateResponsibleDto model module.
 * @module model/CreateResponsibleDto
 * @version 1.0
 */
class CreateResponsibleDto {
    /**
     * Constructs a new <code>CreateResponsibleDto</code>.
     * @alias module:model/CreateResponsibleDto
     * @param name {String} 
     * @param type {module:model/CreateResponsibleDto.TypeEnum} 
     * @param is_active {Boolean} 
     */
    constructor(name, type, is_active) { 
        
        CreateResponsibleDto.initialize(this, name, type, is_active);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, type, is_active) { 
        obj['name'] = name;
        obj['type'] = type;
        obj['is_active'] = is_active;
    }

    /**
     * Constructs a <code>CreateResponsibleDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateResponsibleDto} obj Optional instance to populate.
     * @return {module:model/CreateResponsibleDto} The populated <code>CreateResponsibleDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateResponsibleDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
CreateResponsibleDto.prototype['name'] = undefined;

/**
 * @member {module:model/CreateResponsibleDto.TypeEnum} type
 */
CreateResponsibleDto.prototype['type'] = undefined;

/**
 * @member {Boolean} is_active
 */
CreateResponsibleDto.prototype['is_active'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CreateResponsibleDto['TypeEnum'] = {

    /**
     * value: "commercial"
     * @const
     */
    "commercial": "commercial",

    /**
     * value: "support"
     * @const
     */
    "support": "support"
};



export default CreateResponsibleDto;

