/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CreateDebitAddressDTO} from './CreateDebitAddressDTO';

/**
 * The CustomerDTO model module.
 * @module model/CustomerDTO
 * @version 1.0
 */
export class CustomerDTO {
  /**
   * Constructs a new <code>CustomerDTO</code>.
   * @alias module:model/CustomerDTO
   * @class
   * @param firstName {String} 
   * @param lastName {String} 
   */
  constructor(firstName, lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
  }

  /**
   * Constructs a <code>CustomerDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomerDTO} obj Optional instance to populate.
   * @return {module:model/CustomerDTO} The populated <code>CustomerDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CustomerDTO();
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('document'))
        obj.document = ApiClient.convertToType(data['document'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('ip'))
        obj.ip = ApiClient.convertToType(data['ip'], 'String');
      if (data.hasOwnProperty('billing_address'))
        obj.billingAddress = CreateDebitAddressDTO.constructFromObject(data['billing_address']);
    }
    return obj;
  }
}

/**
 * @member {String} firstName
 */
CustomerDTO.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
CustomerDTO.prototype.lastName = undefined;

/**
 * Número do CPF/CNPJ do comprador
 * @member {String} document
 */
CustomerDTO.prototype.document = undefined;

/**
 * @member {String} email
 */
CustomerDTO.prototype.email = undefined;

/**
 * @member {String} ip
 */
CustomerDTO.prototype.ip = undefined;

/**
 * @member {module:model/CreateDebitAddressDTO} billingAddress
 */
CustomerDTO.prototype.billingAddress = undefined;

