/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EditSellerCredentialDto model module.
 * @module model/EditSellerCredentialDto
 * @version 1.0
 */
class EditSellerCredentialDto {
    /**
     * Constructs a new <code>EditSellerCredentialDto</code>.
     * @alias module:model/EditSellerCredentialDto
     * @param client_id {String} 
     */
    constructor(client_id) { 
        
        EditSellerCredentialDto.initialize(this, client_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, client_id) { 
        obj['client_id'] = client_id;
    }

    /**
     * Constructs a <code>EditSellerCredentialDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EditSellerCredentialDto} obj Optional instance to populate.
     * @return {module:model/EditSellerCredentialDto} The populated <code>EditSellerCredentialDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EditSellerCredentialDto();

            if (data.hasOwnProperty('api_key')) {
                obj['api_key'] = ApiClient.convertToType(data['api_key'], 'String');
            }
            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} api_key
 */
EditSellerCredentialDto.prototype['api_key'] = undefined;

/**
 * @member {String} client_id
 */
EditSellerCredentialDto.prototype['client_id'] = undefined;






export default EditSellerCredentialDto;

