/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CurrencyEnum} from './CurrencyEnum';

/**
 * The FeeTransactionDto model module.
 * @module model/FeeTransactionDto
 * @version 1.0
 */
export class FeeTransactionDto {
  /**
   * Constructs a new <code>FeeTransactionDto</code>.
   * @alias module:model/FeeTransactionDto
   * @class
   * @param amount {Number} 
   * @param realAmount {Number} 
   * @param currency {module:model/CurrencyEnum} 
   * @param type {String} 
   * @param description {String} 
   */
  constructor(amount, realAmount, currency, type, description) {
    this.amount = amount;
    this.realAmount = realAmount;
    this.currency = currency;
    this.type = type;
    this.description = description;
  }

  /**
   * Constructs a <code>FeeTransactionDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FeeTransactionDto} obj Optional instance to populate.
   * @return {module:model/FeeTransactionDto} The populated <code>FeeTransactionDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FeeTransactionDto();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('real_amount'))
        obj.realAmount = ApiClient.convertToType(data['real_amount'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = CurrencyEnum.constructFromObject(data['currency']);
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} amount
 */
FeeTransactionDto.prototype.amount = undefined;

/**
 * @member {Number} realAmount
 */
FeeTransactionDto.prototype.realAmount = undefined;

/**
 * @member {module:model/CurrencyEnum} currency
 */
FeeTransactionDto.prototype.currency = undefined;

/**
 * @member {String} type
 */
FeeTransactionDto.prototype.type = undefined;

/**
 * @member {String} description
 */
FeeTransactionDto.prototype.description = undefined;

