/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ForgotPasswordRequestDto model module.
 * @module model/ForgotPasswordRequestDto
 * @version 1.0
 */
class ForgotPasswordRequestDto {
    /**
     * Constructs a new <code>ForgotPasswordRequestDto</code>.
     * @alias module:model/ForgotPasswordRequestDto
     * @param email {String} 
     */
    constructor(email) { 
        
        ForgotPasswordRequestDto.initialize(this, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email) { 
        obj['email'] = email;
    }

    /**
     * Constructs a <code>ForgotPasswordRequestDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ForgotPasswordRequestDto} obj Optional instance to populate.
     * @return {module:model/ForgotPasswordRequestDto} The populated <code>ForgotPasswordRequestDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForgotPasswordRequestDto();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} email
 */
ForgotPasswordRequestDto.prototype['email'] = undefined;






export default ForgotPasswordRequestDto;

