/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetBankAccountDto model module.
 * @module model/GetBankAccountDto
 * @version 1.0
 */
class GetBankAccountDto {
    /**
     * Constructs a new <code>GetBankAccountDto</code>.
     * @alias module:model/GetBankAccountDto
     * @param agency_digit {String} 
     * @param pix_key {String} 
     * @param bank_code {String} 
     * @param agency_number {String} 
     * @param account_number {String} 
     * @param account_digit {String} 
     * @param type_account {module:model/GetBankAccountDto.TypeAccountEnum} 
     */
    constructor(agency_digit, pix_key, bank_code, agency_number, account_number, account_digit, type_account) { 
        
        GetBankAccountDto.initialize(this, agency_digit, pix_key, bank_code, agency_number, account_number, account_digit, type_account);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, agency_digit, pix_key, bank_code, agency_number, account_number, account_digit, type_account) { 
        obj['agency_digit'] = agency_digit;
        obj['pix_key'] = pix_key;
        obj['bank_code'] = bank_code;
        obj['agency_number'] = agency_number;
        obj['account_number'] = account_number;
        obj['account_digit'] = account_digit;
        obj['type_account'] = type_account;
    }

    /**
     * Constructs a <code>GetBankAccountDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetBankAccountDto} obj Optional instance to populate.
     * @return {module:model/GetBankAccountDto} The populated <code>GetBankAccountDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetBankAccountDto();

            if (data.hasOwnProperty('agency_digit')) {
                obj['agency_digit'] = ApiClient.convertToType(data['agency_digit'], 'String');
            }
            if (data.hasOwnProperty('pix_key')) {
                obj['pix_key'] = ApiClient.convertToType(data['pix_key'], 'String');
            }
            if (data.hasOwnProperty('bank_code')) {
                obj['bank_code'] = ApiClient.convertToType(data['bank_code'], 'String');
            }
            if (data.hasOwnProperty('agency_number')) {
                obj['agency_number'] = ApiClient.convertToType(data['agency_number'], 'String');
            }
            if (data.hasOwnProperty('account_number')) {
                obj['account_number'] = ApiClient.convertToType(data['account_number'], 'String');
            }
            if (data.hasOwnProperty('account_digit')) {
                obj['account_digit'] = ApiClient.convertToType(data['account_digit'], 'String');
            }
            if (data.hasOwnProperty('type_account')) {
                obj['type_account'] = ApiClient.convertToType(data['type_account'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} agency_digit
 */
GetBankAccountDto.prototype['agency_digit'] = undefined;

/**
 * @member {String} pix_key
 */
GetBankAccountDto.prototype['pix_key'] = undefined;

/**
 * @member {String} bank_code
 */
GetBankAccountDto.prototype['bank_code'] = undefined;

/**
 * @member {String} agency_number
 */
GetBankAccountDto.prototype['agency_number'] = undefined;

/**
 * @member {String} account_number
 */
GetBankAccountDto.prototype['account_number'] = undefined;

/**
 * @member {String} account_digit
 */
GetBankAccountDto.prototype['account_digit'] = undefined;

/**
 * @member {module:model/GetBankAccountDto.TypeAccountEnum} type_account
 */
GetBankAccountDto.prototype['type_account'] = undefined;





/**
 * Allowed values for the <code>type_account</code> property.
 * @enum {String}
 * @readonly
 */
GetBankAccountDto['TypeAccountEnum'] = {

    /**
     * value: "current"
     * @const
     */
    "current": "current",

    /**
     * value: "savings"
     * @const
     */
    "savings": "savings"
};



export default GetBankAccountDto;

