/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetCostOptionDto from './GetCostOptionDto';

/**
 * The GetCostPlanDto model module.
 * @module model/GetCostPlanDto
 * @version 1.0
 */
class GetCostPlanDto {
    /**
     * Constructs a new <code>GetCostPlanDto</code>.
     * @alias module:model/GetCostPlanDto
     * @param id {String} 
     * @param name {String} 
     * @param description {String} 
     */
    constructor(id, name, description) { 
        
        GetCostPlanDto.initialize(this, id, name, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, description) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>GetCostPlanDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetCostPlanDto} obj Optional instance to populate.
     * @return {module:model/GetCostPlanDto} The populated <code>GetCostPlanDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetCostPlanDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], [GetCostOptionDto]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
GetCostPlanDto.prototype['id'] = undefined;

/**
 * @member {String} name
 */
GetCostPlanDto.prototype['name'] = undefined;

/**
 * @member {String} description
 */
GetCostPlanDto.prototype['description'] = undefined;

/**
 * @member {Array.<module:model/GetCostOptionDto>} options
 */
GetCostPlanDto.prototype['options'] = undefined;






export default GetCostPlanDto;

