/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetForgotPasswordRequestUserDto model module.
 * @module model/GetForgotPasswordRequestUserDto
 * @version 1.0
 */
export class GetForgotPasswordRequestUserDto {
  /**
   * Constructs a new <code>GetForgotPasswordRequestUserDto</code>.
   * @alias module:model/GetForgotPasswordRequestUserDto
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>GetForgotPasswordRequestUserDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetForgotPasswordRequestUserDto} obj Optional instance to populate.
   * @return {module:model/GetForgotPasswordRequestUserDto} The populated <code>GetForgotPasswordRequestUserDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetForgotPasswordRequestUserDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
GetForgotPasswordRequestUserDto.prototype.name = undefined;

