/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetFileExportRequestUserDto model module.
 * @module model/GetFileExportRequestUserDto
 * @version 1.0
 */
class GetFileExportRequestUserDto {
    /**
     * Constructs a new <code>GetFileExportRequestUserDto</code>.
     * @alias module:model/GetFileExportRequestUserDto
     * @param name {String} 
     */
    constructor(name) { 
        
        GetFileExportRequestUserDto.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>GetFileExportRequestUserDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetFileExportRequestUserDto} obj Optional instance to populate.
     * @return {module:model/GetFileExportRequestUserDto} The populated <code>GetFileExportRequestUserDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetFileExportRequestUserDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
GetFileExportRequestUserDto.prototype['name'] = undefined;






export default GetFileExportRequestUserDto;

