/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetLogoDto model module.
 * @module model/GetLogoDto
 * @version 1.0
 */
export class GetLogoDto {
  /**
   * Constructs a new <code>GetLogoDto</code>.
   * @alias module:model/GetLogoDto
   * @class
   * @param url {String} 
   */
  constructor(url) {
    this.url = url;
  }

  /**
   * Constructs a <code>GetLogoDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetLogoDto} obj Optional instance to populate.
   * @return {module:model/GetLogoDto} The populated <code>GetLogoDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetLogoDto();
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} url
 */
GetLogoDto.prototype.url = undefined;

