/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetProtestLinkSaleDto model module.
 * @module model/GetProtestLinkSaleDto
 * @version 1.0
 */
export class GetProtestLinkSaleDto {
  /**
   * Constructs a new <code>GetProtestLinkSaleDto</code>.
   * @alias module:model/GetProtestLinkSaleDto
   * @class
   * @param id {String} 
   * @param description {String} 
   * @param createdAt {String} 
   * @param updatedAt {String} 
   * @param originalAmount {Number} 
   * @param amount {Number} 
   * @param fee {Number} 
   * @param type {module:model/GetProtestLinkSaleDto.TypeEnum} 
   * @param formPayment {module:model/GetProtestLinkSaleDto.FormPaymentEnum} 
   * @param formattedFormPayment {String} 
   * @param status {module:model/GetProtestLinkSaleDto.StatusEnum} 
   */
  constructor(id, description, createdAt, updatedAt, originalAmount, amount, fee, type, formPayment, formattedFormPayment, status) {
    this.id = id;
    this.description = description;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.originalAmount = originalAmount;
    this.amount = amount;
    this.fee = fee;
    this.type = type;
    this.formPayment = formPayment;
    this.formattedFormPayment = formattedFormPayment;
    this.status = status;
  }

  /**
   * Constructs a <code>GetProtestLinkSaleDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetProtestLinkSaleDto} obj Optional instance to populate.
   * @return {module:model/GetProtestLinkSaleDto} The populated <code>GetProtestLinkSaleDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetProtestLinkSaleDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'String');
      if (data.hasOwnProperty('original_amount'))
        obj.originalAmount = ApiClient.convertToType(data['original_amount'], 'Number');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('fee'))
        obj.fee = ApiClient.convertToType(data['fee'], 'Number');
      if (data.hasOwnProperty('absorb_costs'))
        obj.absorbCosts = ApiClient.convertToType(data['absorb_costs'], ['String']);
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('form_payment'))
        obj.formPayment = ApiClient.convertToType(data['form_payment'], 'String');
      if (data.hasOwnProperty('formatted_form_payment'))
        obj.formattedFormPayment = ApiClient.convertToType(data['formatted_form_payment'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetProtestLinkSaleDto.prototype.id = undefined;

/**
 * @member {String} description
 */
GetProtestLinkSaleDto.prototype.description = undefined;

/**
 * @member {String} createdAt
 */
GetProtestLinkSaleDto.prototype.createdAt = undefined;

/**
 * @member {String} updatedAt
 */
GetProtestLinkSaleDto.prototype.updatedAt = undefined;

/**
 * @member {Number} originalAmount
 */
GetProtestLinkSaleDto.prototype.originalAmount = undefined;

/**
 * @member {Number} amount
 */
GetProtestLinkSaleDto.prototype.amount = undefined;

/**
 * @member {Number} fee
 */
GetProtestLinkSaleDto.prototype.fee = undefined;

/**
 * @member {Array.<String>} absorbCosts
 */
GetProtestLinkSaleDto.prototype.absorbCosts = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
GetProtestLinkSaleDto.TypeEnum = {
  /**
   * value: "boleto"
   * @const
   */
  boleto: "boleto",

  /**
   * value: "pos"
   * @const
   */
  pos: "pos",

  /**
   * value: "payment_link"
   * @const
   */
  paymentLink: "payment_link",

  /**
   * value: "protest_link"
   * @const
   */
  protestLink: "protest_link",

  /**
   * value: "online"
   * @const
   */
  online: "online",

  /**
   * value: "auto_generate_payment_link"
   * @const
   */
  autoGeneratePaymentLink: "auto_generate_payment_link",

  /**
   * value: "auto_generate_protest_link"
   * @const
   */
  autoGenerateProtestLink: "auto_generate_protest_link"
};
/**
 * @member {module:model/GetProtestLinkSaleDto.TypeEnum} type
 */
GetProtestLinkSaleDto.prototype.type = undefined;

/**
 * Allowed values for the <code>formPayment</code> property.
 * @enum {String}
 * @readonly
 */
GetProtestLinkSaleDto.FormPaymentEnum = {
  /**
   * value: "credit"
   * @const
   */
  credit: "credit",

  /**
   * value: "debit"
   * @const
   */
  debit: "debit",

  /**
   * value: "billet"
   * @const
   */
  billet: "billet",

  /**
   * value: "pix"
   * @const
   */
  pix: "pix",

  /**
   * value: "pending"
   * @const
   */
  pending: "pending"
};
/**
 * @member {module:model/GetProtestLinkSaleDto.FormPaymentEnum} formPayment
 */
GetProtestLinkSaleDto.prototype.formPayment = undefined;

/**
 * @member {String} formattedFormPayment
 */
GetProtestLinkSaleDto.prototype.formattedFormPayment = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
GetProtestLinkSaleDto.StatusEnum = {
  /**
   * value: "pending"
   * @const
   */
  pending: "pending",

  /**
   * value: "pending_capture"
   * @const
   */
  pendingCapture: "pending_capture",

  /**
   * value: "in_progress_capture"
   * @const
   */
  inProgressCapture: "in_progress_capture",

  /**
   * value: "succeeded"
   * @const
   */
  succeeded: "succeeded",

  /**
   * value: "canceled"
   * @const
   */
  canceled: "canceled",

  /**
   * value: "pending_cancel"
   * @const
   */
  pendingCancel: "pending_cancel",

  /**
   * value: "abort"
   * @const
   */
  abort: "abort",

  /**
   * value: "failed"
   * @const
   */
  failed: "failed"
};
/**
 * @member {module:model/GetProtestLinkSaleDto.StatusEnum} status
 */
GetProtestLinkSaleDto.prototype.status = undefined;

