/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetSaleSummaryTypeDto model module.
 * @module model/GetSaleSummaryTypeDto
 * @version 1.0
 */
class GetSaleSummaryTypeDto {
    /**
     * Constructs a new <code>GetSaleSummaryTypeDto</code>.
     * @alias module:model/GetSaleSummaryTypeDto
     * @param type_sale {String} 
     * @param type_name {String} 
     * @param financial_volume {Number} 
     * @param gross_volume {Number} 
     * @param number_sales {Number} 
     * @param average {Number} 
     * @param percentage {Number} 
     */
    constructor(type_sale, type_name, financial_volume, gross_volume, number_sales, average, percentage) { 
        
        GetSaleSummaryTypeDto.initialize(this, type_sale, type_name, financial_volume, gross_volume, number_sales, average, percentage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type_sale, type_name, financial_volume, gross_volume, number_sales, average, percentage) { 
        obj['type_sale'] = type_sale;
        obj['type_name'] = type_name;
        obj['financial_volume'] = financial_volume;
        obj['gross_volume'] = gross_volume;
        obj['number_sales'] = number_sales;
        obj['average'] = average;
        obj['percentage'] = percentage;
    }

    /**
     * Constructs a <code>GetSaleSummaryTypeDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetSaleSummaryTypeDto} obj Optional instance to populate.
     * @return {module:model/GetSaleSummaryTypeDto} The populated <code>GetSaleSummaryTypeDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSaleSummaryTypeDto();

            if (data.hasOwnProperty('type_sale')) {
                obj['type_sale'] = ApiClient.convertToType(data['type_sale'], 'String');
            }
            if (data.hasOwnProperty('type_name')) {
                obj['type_name'] = ApiClient.convertToType(data['type_name'], 'String');
            }
            if (data.hasOwnProperty('financial_volume')) {
                obj['financial_volume'] = ApiClient.convertToType(data['financial_volume'], 'Number');
            }
            if (data.hasOwnProperty('gross_volume')) {
                obj['gross_volume'] = ApiClient.convertToType(data['gross_volume'], 'Number');
            }
            if (data.hasOwnProperty('number_sales')) {
                obj['number_sales'] = ApiClient.convertToType(data['number_sales'], 'Number');
            }
            if (data.hasOwnProperty('average')) {
                obj['average'] = ApiClient.convertToType(data['average'], 'Number');
            }
            if (data.hasOwnProperty('percentage')) {
                obj['percentage'] = ApiClient.convertToType(data['percentage'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type_sale
 */
GetSaleSummaryTypeDto.prototype['type_sale'] = undefined;

/**
 * @member {String} type_name
 */
GetSaleSummaryTypeDto.prototype['type_name'] = undefined;

/**
 * @member {Number} financial_volume
 */
GetSaleSummaryTypeDto.prototype['financial_volume'] = undefined;

/**
 * @member {Number} gross_volume
 */
GetSaleSummaryTypeDto.prototype['gross_volume'] = undefined;

/**
 * @member {Number} number_sales
 */
GetSaleSummaryTypeDto.prototype['number_sales'] = undefined;

/**
 * @member {Number} average
 */
GetSaleSummaryTypeDto.prototype['average'] = undefined;

/**
 * @member {Number} percentage
 */
GetSaleSummaryTypeDto.prototype['percentage'] = undefined;






export default GetSaleSummaryTypeDto;

