/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetSellerAcceptedPaymentMethodsDto model module.
 * @module model/GetSellerAcceptedPaymentMethodsDto
 * @version 1.0
 */
class GetSellerAcceptedPaymentMethodsDto {
    /**
     * Constructs a new <code>GetSellerAcceptedPaymentMethodsDto</code>.
     * @alias module:model/GetSellerAcceptedPaymentMethodsDto
     * @param billet_payment_is_permitted {Boolean} 
     * @param qrcode_payment_is_permitted {Boolean} 
     * @param card_payment_is_permitted {Boolean} 
     */
    constructor(billet_payment_is_permitted, qrcode_payment_is_permitted, card_payment_is_permitted) { 
        
        GetSellerAcceptedPaymentMethodsDto.initialize(this, billet_payment_is_permitted, qrcode_payment_is_permitted, card_payment_is_permitted);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, billet_payment_is_permitted, qrcode_payment_is_permitted, card_payment_is_permitted) { 
        obj['billet_payment_is_permitted'] = billet_payment_is_permitted;
        obj['qrcode_payment_is_permitted'] = qrcode_payment_is_permitted;
        obj['card_payment_is_permitted'] = card_payment_is_permitted;
    }

    /**
     * Constructs a <code>GetSellerAcceptedPaymentMethodsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetSellerAcceptedPaymentMethodsDto} obj Optional instance to populate.
     * @return {module:model/GetSellerAcceptedPaymentMethodsDto} The populated <code>GetSellerAcceptedPaymentMethodsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSellerAcceptedPaymentMethodsDto();

            if (data.hasOwnProperty('billet_payment_is_permitted')) {
                obj['billet_payment_is_permitted'] = ApiClient.convertToType(data['billet_payment_is_permitted'], 'Boolean');
            }
            if (data.hasOwnProperty('qrcode_payment_is_permitted')) {
                obj['qrcode_payment_is_permitted'] = ApiClient.convertToType(data['qrcode_payment_is_permitted'], 'Boolean');
            }
            if (data.hasOwnProperty('card_payment_is_permitted')) {
                obj['card_payment_is_permitted'] = ApiClient.convertToType(data['card_payment_is_permitted'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} billet_payment_is_permitted
 */
GetSellerAcceptedPaymentMethodsDto.prototype['billet_payment_is_permitted'] = undefined;

/**
 * @member {Boolean} qrcode_payment_is_permitted
 */
GetSellerAcceptedPaymentMethodsDto.prototype['qrcode_payment_is_permitted'] = undefined;

/**
 * @member {Boolean} card_payment_is_permitted
 */
GetSellerAcceptedPaymentMethodsDto.prototype['card_payment_is_permitted'] = undefined;






export default GetSellerAcceptedPaymentMethodsDto;

