/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetSalePayerAddressDto model module.
 * @module model/GetSalePayerAddressDto
 * @version 1.0
 */
export class GetSalePayerAddressDto {
  /**
   * Constructs a new <code>GetSalePayerAddressDto</code>.
   * @alias module:model/GetSalePayerAddressDto
   * @class
   * @param complement {String} 
   * @param district {String} 
   * @param street {String} 
   * @param _number {String} 
   * @param zipcode {String} 
   * @param state {String} 
   * @param city {String} 
   */
  constructor(complement, district, street, _number, zipcode, state, city) {
    this.complement = complement;
    this.district = district;
    this.street = street;
    this._number = _number;
    this.zipcode = zipcode;
    this.state = state;
    this.city = city;
  }

  /**
   * Constructs a <code>GetSalePayerAddressDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetSalePayerAddressDto} obj Optional instance to populate.
   * @return {module:model/GetSalePayerAddressDto} The populated <code>GetSalePayerAddressDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetSalePayerAddressDto();
      if (data.hasOwnProperty('complement'))
        obj.complement = ApiClient.convertToType(data['complement'], 'String');
      if (data.hasOwnProperty('district'))
        obj.district = ApiClient.convertToType(data['district'], 'String');
      if (data.hasOwnProperty('street'))
        obj.street = ApiClient.convertToType(data['street'], 'String');
      if (data.hasOwnProperty('number'))
        obj._number = ApiClient.convertToType(data['number'], 'String');
      if (data.hasOwnProperty('zipcode'))
        obj.zipcode = ApiClient.convertToType(data['zipcode'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} complement
 */
GetSalePayerAddressDto.prototype.complement = undefined;

/**
 * @member {String} district
 */
GetSalePayerAddressDto.prototype.district = undefined;

/**
 * @member {String} street
 */
GetSalePayerAddressDto.prototype.street = undefined;

/**
 * @member {String} _number
 */
GetSalePayerAddressDto.prototype._number = undefined;

/**
 * @member {String} zipcode
 */
GetSalePayerAddressDto.prototype.zipcode = undefined;

/**
 * @member {String} state
 */
GetSalePayerAddressDto.prototype.state = undefined;

/**
 * @member {String} city
 */
GetSalePayerAddressDto.prototype.city = undefined;

