/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetSaleSummaryChartDto model module.
 * @module model/GetSaleSummaryChartDto
 * @version 1.0
 */
class GetSaleSummaryChartDto {
    /**
     * Constructs a new <code>GetSaleSummaryChartDto</code>.
     * @alias module:model/GetSaleSummaryChartDto
     * @param sales_progression {Array.<Number>} 
     * @param months_progression {Array.<String>} 
     * @param average_ticket {Number} 
     * @param total_sales {Number} 
     * @param total_payers {Number} 
     * @param financial_success_sale {Number} 
     * @param financial_canceled_sale {Number} 
     * @param financial_pending_sale {Number} 
     * @param sales_day_progression {Array.<Number>} 
     * @param day_progression {Array.<String>} 
     * @param ticket_day_progression {Array.<Number>} 
     * @param ticket_month_progression {Array.<Number>} 
     * @param sales_total_day_progression {Array.<Number>} 
     * @param sales_total_month_progression {Array.<Number>} 
     */
    constructor(sales_progression, months_progression, average_ticket, total_sales, total_payers, financial_success_sale, financial_canceled_sale, financial_pending_sale, sales_day_progression, day_progression, ticket_day_progression, ticket_month_progression, sales_total_day_progression, sales_total_month_progression) { 
        
        GetSaleSummaryChartDto.initialize(this, sales_progression, months_progression, average_ticket, total_sales, total_payers, financial_success_sale, financial_canceled_sale, financial_pending_sale, sales_day_progression, day_progression, ticket_day_progression, ticket_month_progression, sales_total_day_progression, sales_total_month_progression);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sales_progression, months_progression, average_ticket, total_sales, total_payers, financial_success_sale, financial_canceled_sale, financial_pending_sale, sales_day_progression, day_progression, ticket_day_progression, ticket_month_progression, sales_total_day_progression, sales_total_month_progression) { 
        obj['sales_progression'] = sales_progression;
        obj['months_progression'] = months_progression;
        obj['average_ticket'] = average_ticket;
        obj['total_sales'] = total_sales;
        obj['total_payers'] = total_payers;
        obj['financial_success_sale'] = financial_success_sale;
        obj['financial_canceled_sale'] = financial_canceled_sale;
        obj['financial_pending_sale'] = financial_pending_sale;
        obj['sales_day_progression'] = sales_day_progression;
        obj['day_progression'] = day_progression;
        obj['ticket_day_progression'] = ticket_day_progression;
        obj['ticket_month_progression'] = ticket_month_progression;
        obj['sales_total_day_progression'] = sales_total_day_progression;
        obj['sales_total_month_progression'] = sales_total_month_progression;
    }

    /**
     * Constructs a <code>GetSaleSummaryChartDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetSaleSummaryChartDto} obj Optional instance to populate.
     * @return {module:model/GetSaleSummaryChartDto} The populated <code>GetSaleSummaryChartDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSaleSummaryChartDto();

            if (data.hasOwnProperty('sales_progression')) {
                obj['sales_progression'] = ApiClient.convertToType(data['sales_progression'], ['Number']);
            }
            if (data.hasOwnProperty('months_progression')) {
                obj['months_progression'] = ApiClient.convertToType(data['months_progression'], ['String']);
            }
            if (data.hasOwnProperty('average_ticket')) {
                obj['average_ticket'] = ApiClient.convertToType(data['average_ticket'], 'Number');
            }
            if (data.hasOwnProperty('total_sales')) {
                obj['total_sales'] = ApiClient.convertToType(data['total_sales'], 'Number');
            }
            if (data.hasOwnProperty('total_payers')) {
                obj['total_payers'] = ApiClient.convertToType(data['total_payers'], 'Number');
            }
            if (data.hasOwnProperty('financial_success_sale')) {
                obj['financial_success_sale'] = ApiClient.convertToType(data['financial_success_sale'], 'Number');
            }
            if (data.hasOwnProperty('financial_canceled_sale')) {
                obj['financial_canceled_sale'] = ApiClient.convertToType(data['financial_canceled_sale'], 'Number');
            }
            if (data.hasOwnProperty('financial_pending_sale')) {
                obj['financial_pending_sale'] = ApiClient.convertToType(data['financial_pending_sale'], 'Number');
            }
            if (data.hasOwnProperty('sales_day_progression')) {
                obj['sales_day_progression'] = ApiClient.convertToType(data['sales_day_progression'], ['Number']);
            }
            if (data.hasOwnProperty('day_progression')) {
                obj['day_progression'] = ApiClient.convertToType(data['day_progression'], ['String']);
            }
            if (data.hasOwnProperty('ticket_day_progression')) {
                obj['ticket_day_progression'] = ApiClient.convertToType(data['ticket_day_progression'], ['Number']);
            }
            if (data.hasOwnProperty('ticket_month_progression')) {
                obj['ticket_month_progression'] = ApiClient.convertToType(data['ticket_month_progression'], ['Number']);
            }
            if (data.hasOwnProperty('sales_total_day_progression')) {
                obj['sales_total_day_progression'] = ApiClient.convertToType(data['sales_total_day_progression'], ['Number']);
            }
            if (data.hasOwnProperty('sales_total_month_progression')) {
                obj['sales_total_month_progression'] = ApiClient.convertToType(data['sales_total_month_progression'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} sales_progression
 */
GetSaleSummaryChartDto.prototype['sales_progression'] = undefined;

/**
 * @member {Array.<String>} months_progression
 */
GetSaleSummaryChartDto.prototype['months_progression'] = undefined;

/**
 * @member {Number} average_ticket
 */
GetSaleSummaryChartDto.prototype['average_ticket'] = undefined;

/**
 * @member {Number} total_sales
 */
GetSaleSummaryChartDto.prototype['total_sales'] = undefined;

/**
 * @member {Number} total_payers
 */
GetSaleSummaryChartDto.prototype['total_payers'] = undefined;

/**
 * @member {Number} financial_success_sale
 */
GetSaleSummaryChartDto.prototype['financial_success_sale'] = undefined;

/**
 * @member {Number} financial_canceled_sale
 */
GetSaleSummaryChartDto.prototype['financial_canceled_sale'] = undefined;

/**
 * @member {Number} financial_pending_sale
 */
GetSaleSummaryChartDto.prototype['financial_pending_sale'] = undefined;

/**
 * @member {Array.<Number>} sales_day_progression
 */
GetSaleSummaryChartDto.prototype['sales_day_progression'] = undefined;

/**
 * @member {Array.<String>} day_progression
 */
GetSaleSummaryChartDto.prototype['day_progression'] = undefined;

/**
 * @member {Array.<Number>} ticket_day_progression
 */
GetSaleSummaryChartDto.prototype['ticket_day_progression'] = undefined;

/**
 * @member {Array.<Number>} ticket_month_progression
 */
GetSaleSummaryChartDto.prototype['ticket_month_progression'] = undefined;

/**
 * @member {Array.<Number>} sales_total_day_progression
 */
GetSaleSummaryChartDto.prototype['sales_total_day_progression'] = undefined;

/**
 * @member {Array.<Number>} sales_total_month_progression
 */
GetSaleSummaryChartDto.prototype['sales_total_month_progression'] = undefined;






export default GetSaleSummaryChartDto;

