/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetSplitRulesSimulationDto model module.
 * @module model/GetSplitRulesSimulationDto
 * @version 1.0
 */
class GetSplitRulesSimulationDto {
    /**
     * Constructs a new <code>GetSplitRulesSimulationDto</code>.
     * @alias module:model/GetSplitRulesSimulationDto
     * @param amount {Number} 
     * @param seller {String} 
     */
    constructor(amount, seller) { 
        
        GetSplitRulesSimulationDto.initialize(this, amount, seller);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, seller) { 
        obj['amount'] = amount;
        obj['seller'] = seller;
    }

    /**
     * Constructs a <code>GetSplitRulesSimulationDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetSplitRulesSimulationDto} obj Optional instance to populate.
     * @return {module:model/GetSplitRulesSimulationDto} The populated <code>GetSplitRulesSimulationDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetSplitRulesSimulationDto();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('seller')) {
                obj['seller'] = ApiClient.convertToType(data['seller'], 'String');
            }
            if (data.hasOwnProperty('no_cost')) {
                obj['no_cost'] = ApiClient.convertToType(data['no_cost'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} amount
 */
GetSplitRulesSimulationDto.prototype['amount'] = undefined;

/**
 * @member {String} seller
 */
GetSplitRulesSimulationDto.prototype['seller'] = undefined;

/**
 * @member {Boolean} no_cost
 */
GetSplitRulesSimulationDto.prototype['no_cost'] = undefined;






export default GetSplitRulesSimulationDto;

