/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetUserSellerDto} from './GetUserSellerDto';

/**
 * The GetUserDto model module.
 * @module model/GetUserDto
 * @version 1.0
 */
export class GetUserDto {
  /**
   * Constructs a new <code>GetUserDto</code>.
   * @alias module:model/GetUserDto
   * @class
   * @param id {String} 
   * @param name {String} 
   * @param email {String} 
   * @param type {module:model/GetUserDto.TypeEnum} 
   * @param role {module:model/GetUserDto.RoleEnum} 
   * @param status {module:model/GetUserDto.StatusEnum} 
   * @param createdAt {String} 
   * @param seller {module:model/GetUserSellerDto} 
   */
  constructor(id, name, email, type, role, status, createdAt, seller) {
    this.id = id;
    this.name = name;
    this.email = email;
    this.type = type;
    this.role = role;
    this.status = status;
    this.createdAt = createdAt;
    this.seller = seller;
  }

  /**
   * Constructs a <code>GetUserDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetUserDto} obj Optional instance to populate.
   * @return {module:model/GetUserDto} The populated <code>GetUserDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetUserDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('seller'))
        obj.seller = GetUserSellerDto.constructFromObject(data['seller']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
GetUserDto.prototype.id = undefined;

/**
 * @member {String} name
 */
GetUserDto.prototype.name = undefined;

/**
 * @member {String} email
 */
GetUserDto.prototype.email = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
GetUserDto.TypeEnum = {
  /**
   * value: "merchant"
   * @const
   */
  merchant: "merchant",

  /**
   * value: "seller"
   * @const
   */
  seller: "seller",

  /**
   * value: "backoffice"
   * @const
   */
  backoffice: "backoffice"
};
/**
 * @member {module:model/GetUserDto.TypeEnum} type
 */
GetUserDto.prototype.type = undefined;

/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
GetUserDto.RoleEnum = {
  /**
   * value: "operational_basic"
   * @const
   */
  operationalBasic: "operational_basic",

  /**
   * value: "operational_advanced"
   * @const
   */
  operationalAdvanced: "operational_advanced",

  /**
   * value: "financial"
   * @const
   */
  financial: "financial",

  /**
   * value: "admin"
   * @const
   */
  admin: "admin",

  /**
   * value: "admin_not_cancel"
   * @const
   */
  adminNotCancel: "admin_not_cancel"
};
/**
 * @member {module:model/GetUserDto.RoleEnum} role
 */
GetUserDto.prototype.role = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
GetUserDto.StatusEnum = {
  /**
   * value: "active"
   * @const
   */
  active: "active",

  /**
   * value: "inactive"
   * @const
   */
  inactive: "inactive",

  /**
   * value: "pending"
   * @const
   */
  pending: "pending"
};
/**
 * @member {module:model/GetUserDto.StatusEnum} status
 */
GetUserDto.prototype.status = undefined;

/**
 * @member {String} createdAt
 */
GetUserDto.prototype.createdAt = undefined;

/**
 * @member {module:model/GetUserSellerDto} seller
 */
GetUserDto.prototype.seller = undefined;

