/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IncludePaymentTypeDto model module.
 * @module model/IncludePaymentTypeDto
 * @version 1.0
 */
export class IncludePaymentTypeDto {
  /**
   * Constructs a new <code>IncludePaymentTypeDto</code>.
   * @alias module:model/IncludePaymentTypeDto
   * @class
   * @param code {String} 
   * @param fee {Number} 
   * @param description {String} 
   * @param installments {Number} 
   * @param operationMode {module:model/IncludePaymentTypeDto.OperationModeEnum} 
   */
  constructor(code, fee, description, installments, operationMode) {
    this.code = code;
    this.fee = fee;
    this.description = description;
    this.installments = installments;
    this.operationMode = operationMode;
  }

  /**
   * Constructs a <code>IncludePaymentTypeDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IncludePaymentTypeDto} obj Optional instance to populate.
   * @return {module:model/IncludePaymentTypeDto} The populated <code>IncludePaymentTypeDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IncludePaymentTypeDto();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('fee'))
        obj.fee = ApiClient.convertToType(data['fee'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('installments'))
        obj.installments = ApiClient.convertToType(data['installments'], 'Number');
      if (data.hasOwnProperty('operation_mode'))
        obj.operationMode = ApiClient.convertToType(data['operation_mode'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} code
 */
IncludePaymentTypeDto.prototype.code = undefined;

/**
 * @member {Number} fee
 */
IncludePaymentTypeDto.prototype.fee = undefined;

/**
 * @member {String} description
 */
IncludePaymentTypeDto.prototype.description = undefined;

/**
 * @member {Number} installments
 */
IncludePaymentTypeDto.prototype.installments = undefined;

/**
 * Allowed values for the <code>operationMode</code> property.
 * @enum {String}
 * @readonly
 */
IncludePaymentTypeDto.OperationModeEnum = {
  /**
   * value: "credit"
   * @const
   */
  credit: "credit",

  /**
   * value: "debit"
   * @const
   */
  debit: "debit",

  /**
   * value: "pix"
   * @const
   */
  pix: "pix",

  /**
   * value: "billet"
   * @const
   */
  billet: "billet"
};
/**
 * @member {module:model/IncludePaymentTypeDto.OperationModeEnum} operationMode
 */
IncludePaymentTypeDto.prototype.operationMode = undefined;

