/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IncludeSalePlanDto model module.
 * @module model/IncludeSalePlanDto
 * @version 1.0
 */
class IncludeSalePlanDto {
    /**
     * Constructs a new <code>IncludeSalePlanDto</code>.
     * @alias module:model/IncludeSalePlanDto
     * @param sale_plan_id {String} 
     */
    constructor(sale_plan_id) { 
        
        IncludeSalePlanDto.initialize(this, sale_plan_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sale_plan_id) { 
        obj['sale_plan_id'] = sale_plan_id;
    }

    /**
     * Constructs a <code>IncludeSalePlanDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IncludeSalePlanDto} obj Optional instance to populate.
     * @return {module:model/IncludeSalePlanDto} The populated <code>IncludeSalePlanDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IncludeSalePlanDto();

            if (data.hasOwnProperty('sale_plan_id')) {
                obj['sale_plan_id'] = ApiClient.convertToType(data['sale_plan_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} sale_plan_id
 */
IncludeSalePlanDto.prototype['sale_plan_id'] = undefined;






export default IncludeSalePlanDto;

