/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InstallmentPlanDTO model module.
 * @module model/InstallmentPlanDTO
 * @version 1.0
 */
export class InstallmentPlanDTO {
  /**
   * Constructs a new <code>InstallmentPlanDTO</code>.
   * @alias module:model/InstallmentPlanDTO
   * @class
   * @param numberInstallments {Number} 
   */
  constructor(numberInstallments) {
    this.numberInstallments = numberInstallments;
  }

  /**
   * Constructs a <code>InstallmentPlanDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InstallmentPlanDTO} obj Optional instance to populate.
   * @return {module:model/InstallmentPlanDTO} The populated <code>InstallmentPlanDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InstallmentPlanDTO();
      if (data.hasOwnProperty('number_installments'))
        obj.numberInstallments = ApiClient.convertToType(data['number_installments'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} numberInstallments
 */
InstallmentPlanDTO.prototype.numberInstallments = undefined;

