/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Logo model module.
 * @module model/Logo
 * @version 1.0
 */
class Logo {
    /**
     * Constructs a new <code>Logo</code>.
     * @alias module:model/Logo
     * @param key {String} 
     * @param original_name {String} 
     * @param mimetype {String} 
     * @param filename {String} 
     * @param extension {module:model/Logo.ExtensionEnum} 
     * @param created_at {String} 
     */
    constructor(key, original_name, mimetype, filename, extension, created_at) { 
        
        Logo.initialize(this, key, original_name, mimetype, filename, extension, created_at);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key, original_name, mimetype, filename, extension, created_at) { 
        obj['key'] = key;
        obj['original_name'] = original_name;
        obj['mimetype'] = mimetype;
        obj['filename'] = filename;
        obj['extension'] = extension;
        obj['created_at'] = created_at;
    }

    /**
     * Constructs a <code>Logo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Logo} obj Optional instance to populate.
     * @return {module:model/Logo} The populated <code>Logo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Logo();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('original_name')) {
                obj['original_name'] = ApiClient.convertToType(data['original_name'], 'String');
            }
            if (data.hasOwnProperty('mimetype')) {
                obj['mimetype'] = ApiClient.convertToType(data['mimetype'], 'String');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
            if (data.hasOwnProperty('extension')) {
                obj['extension'] = ApiClient.convertToType(data['extension'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Logo.prototype['id'] = undefined;

/**
 * @member {String} key
 */
Logo.prototype['key'] = undefined;

/**
 * @member {String} original_name
 */
Logo.prototype['original_name'] = undefined;

/**
 * @member {String} mimetype
 */
Logo.prototype['mimetype'] = undefined;

/**
 * @member {String} filename
 */
Logo.prototype['filename'] = undefined;

/**
 * @member {module:model/Logo.ExtensionEnum} extension
 */
Logo.prototype['extension'] = undefined;

/**
 * @member {String} url
 */
Logo.prototype['url'] = undefined;

/**
 * @member {String} created_at
 */
Logo.prototype['created_at'] = undefined;

/**
 * @member {String} updated_at
 */
Logo.prototype['updated_at'] = undefined;





/**
 * Allowed values for the <code>extension</code> property.
 * @enum {String}
 * @readonly
 */
Logo['ExtensionEnum'] = {

    /**
     * value: "png"
     * @const
     */
    "png": "png",

    /**
     * value: "jpeg"
     * @const
     */
    "jpeg": "jpeg",

    /**
     * value: "jpg"
     * @const
     */
    "jpg": "jpg"
};



export default Logo;

