/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PaginatedDto model module.
 * @module model/PaginatedDto
 * @version 1.0
 */
export class PaginatedDto {
  /**
   * Constructs a new <code>PaginatedDto</code>.
   * @alias module:model/PaginatedDto
   * @class
   * @param currentPage {Number} 
   * @param totalPages {Number} 
   * @param limit {Number} 
   * @param start {Number} 
   * @param end {Number} 
   * @param totalItems {Number} 
   * @param hasMore {Boolean} 
   * @param results {Array.<String>} 
   * @param additionalData {Object} 
   */
  constructor(currentPage, totalPages, limit, start, end, totalItems, hasMore, results, additionalData) {
    this.currentPage = currentPage;
    this.totalPages = totalPages;
    this.limit = limit;
    this.start = start;
    this.end = end;
    this.totalItems = totalItems;
    this.hasMore = hasMore;
    this.results = results;
    this.additionalData = additionalData;
  }

  /**
   * Constructs a <code>PaginatedDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaginatedDto} obj Optional instance to populate.
   * @return {module:model/PaginatedDto} The populated <code>PaginatedDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PaginatedDto();
      if (data.hasOwnProperty('current_page'))
        obj.currentPage = ApiClient.convertToType(data['current_page'], 'Number');
      if (data.hasOwnProperty('total_pages'))
        obj.totalPages = ApiClient.convertToType(data['total_pages'], 'Number');
      if (data.hasOwnProperty('limit'))
        obj.limit = ApiClient.convertToType(data['limit'], 'Number');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'Number');
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'Number');
      if (data.hasOwnProperty('total_items'))
        obj.totalItems = ApiClient.convertToType(data['total_items'], 'Number');
      if (data.hasOwnProperty('has_more'))
        obj.hasMore = ApiClient.convertToType(data['has_more'], 'Boolean');
      if (data.hasOwnProperty('results'))
        obj.results = ApiClient.convertToType(data['results'], ['String']);
      if (data.hasOwnProperty('additional_data'))
        obj.additionalData = ApiClient.convertToType(data['additional_data'], Object);
    }
    return obj;
  }
}

/**
 * @member {Number} currentPage
 */
PaginatedDto.prototype.currentPage = undefined;

/**
 * @member {Number} totalPages
 */
PaginatedDto.prototype.totalPages = undefined;

/**
 * @member {Number} limit
 */
PaginatedDto.prototype.limit = undefined;

/**
 * @member {Number} start
 */
PaginatedDto.prototype.start = undefined;

/**
 * @member {Number} end
 */
PaginatedDto.prototype.end = undefined;

/**
 * @member {Number} totalItems
 */
PaginatedDto.prototype.totalItems = undefined;

/**
 * @member {Boolean} hasMore
 */
PaginatedDto.prototype.hasMore = undefined;

/**
 * @member {Array.<String>} results
 */
PaginatedDto.prototype.results = undefined;

/**
 * @member {Object} additionalData
 */
PaginatedDto.prototype.additionalData = undefined;

