/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CreateSplitRulesDto} from './CreateSplitRulesDto';

/**
 * The PaymentPosRequestDTOV2 model module.
 * @module model/PaymentPosRequestDTOV2
 * @version 1.0
 */
export class PaymentPosRequestDTOV2 {
  /**
   * Constructs a new <code>PaymentPosRequestDTOV2</code>.
   * @alias module:model/PaymentPosRequestDTOV2
   * @class
   * @param terminalId {String} 
   * @param amount {Number} 
   * @param isDebit {Boolean} 
   * @param instalments {Number} 
   * @param serviceId {String} 
   * @param isPix {Boolean} 
   * @param hasSplitRules {Boolean} 
   * @param splitRules {Array.<module:model/CreateSplitRulesDto>} 
   */
  constructor(terminalId, amount, isDebit, instalments, serviceId, isPix, hasSplitRules, splitRules) {
    this.terminalId = terminalId;
    this.amount = amount;
    this.isDebit = isDebit;
    this.instalments = instalments;
    this.serviceId = serviceId;
    this.isPix = isPix;
    this.hasSplitRules = hasSplitRules;
    this.splitRules = splitRules;
  }

  /**
   * Constructs a <code>PaymentPosRequestDTOV2</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentPosRequestDTOV2} obj Optional instance to populate.
   * @return {module:model/PaymentPosRequestDTOV2} The populated <code>PaymentPosRequestDTOV2</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PaymentPosRequestDTOV2();
      if (data.hasOwnProperty('terminal_id'))
        obj.terminalId = ApiClient.convertToType(data['terminal_id'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('is_debit'))
        obj.isDebit = ApiClient.convertToType(data['is_debit'], 'Boolean');
      if (data.hasOwnProperty('instalments'))
        obj.instalments = ApiClient.convertToType(data['instalments'], 'Number');
      if (data.hasOwnProperty('service_id'))
        obj.serviceId = ApiClient.convertToType(data['service_id'], 'String');
      if (data.hasOwnProperty('is_pix'))
        obj.isPix = ApiClient.convertToType(data['is_pix'], 'Boolean');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('document'))
        obj.document = ApiClient.convertToType(data['document'], 'String');
      if (data.hasOwnProperty('has_split_rules'))
        obj.hasSplitRules = ApiClient.convertToType(data['has_split_rules'], 'Boolean');
      if (data.hasOwnProperty('split_rules'))
        obj.splitRules = ApiClient.convertToType(data['split_rules'], [CreateSplitRulesDto]);
    }
    return obj;
  }
}

/**
 * @member {String} terminalId
 */
PaymentPosRequestDTOV2.prototype.terminalId = undefined;

/**
 * @member {Number} amount
 */
PaymentPosRequestDTOV2.prototype.amount = undefined;

/**
 * @member {Boolean} isDebit
 */
PaymentPosRequestDTOV2.prototype.isDebit = undefined;

/**
 * @member {Number} instalments
 */
PaymentPosRequestDTOV2.prototype.instalments = undefined;

/**
 * @member {String} serviceId
 */
PaymentPosRequestDTOV2.prototype.serviceId = undefined;

/**
 * @member {Boolean} isPix
 */
PaymentPosRequestDTOV2.prototype.isPix = undefined;

/**
 * @member {String} description
 */
PaymentPosRequestDTOV2.prototype.description = undefined;

/**
 * @member {String} document
 */
PaymentPosRequestDTOV2.prototype.document = undefined;

/**
 * @member {Boolean} hasSplitRules
 */
PaymentPosRequestDTOV2.prototype.hasSplitRules = undefined;

/**
 * @member {Array.<module:model/CreateSplitRulesDto>} splitRules
 */
PaymentPosRequestDTOV2.prototype.splitRules = undefined;

