/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentMethodTransactionDto model module.
 * @module model/PaymentMethodTransactionDto
 * @version 1.0
 */
class PaymentMethodTransactionDto {
    /**
     * Constructs a new <code>PaymentMethodTransactionDto</code>.
     * @alias module:model/PaymentMethodTransactionDto
     * @param type {module:model/PaymentMethodTransactionDto.TypeEnum} 
     * @param payer_name {String} 
     * @param metadata {Object} 
     */
    constructor(type, payer_name, metadata) { 
        
        PaymentMethodTransactionDto.initialize(this, type, payer_name, metadata);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, payer_name, metadata) { 
        obj['type'] = type;
        obj['payer_name'] = payer_name;
        obj['metadata'] = metadata;
    }

    /**
     * Constructs a <code>PaymentMethodTransactionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentMethodTransactionDto} obj Optional instance to populate.
     * @return {module:model/PaymentMethodTransactionDto} The populated <code>PaymentMethodTransactionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentMethodTransactionDto();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('payer_name')) {
                obj['payer_name'] = ApiClient.convertToType(data['payer_name'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PaymentMethodTransactionDto.TypeEnum} type
 */
PaymentMethodTransactionDto.prototype['type'] = undefined;

/**
 * @member {String} payer_name
 */
PaymentMethodTransactionDto.prototype['payer_name'] = undefined;

/**
 * @member {Object} metadata
 */
PaymentMethodTransactionDto.prototype['metadata'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
PaymentMethodTransactionDto['TypeEnum'] = {

    /**
     * value: "credit"
     * @const
     */
    "credit": "credit",

    /**
     * value: "debit"
     * @const
     */
    "debit": "debit",

    /**
     * value: "pix"
     * @const
     */
    "pix": "pix",

    /**
     * value: "billet"
     * @const
     */
    "billet": "billet",

    /**
     * value: "pix_pos"
     * @const
     */
    "pix_pos": "pix_pos"
};



export default PaymentMethodTransactionDto;

