/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProtocolDueDateUpdateHistory model module.
 * @module model/ProtocolDueDateUpdateHistory
 * @version 1.0
 */
class ProtocolDueDateUpdateHistory {
    /**
     * Constructs a new <code>ProtocolDueDateUpdateHistory</code>.
     * @alias module:model/ProtocolDueDateUpdateHistory
     * @param user_name {String} 
     * @param created_at {String} 
     * @param created_at_unix_time {Number} 
     * @param before {Object} 
     * @param after {Object} 
     */
    constructor(user_name, created_at, created_at_unix_time, before, after) { 
        
        ProtocolDueDateUpdateHistory.initialize(this, user_name, created_at, created_at_unix_time, before, after);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, user_name, created_at, created_at_unix_time, before, after) { 
        obj['user_name'] = user_name;
        obj['created_at'] = created_at;
        obj['created_at_unix_time'] = created_at_unix_time;
        obj['before'] = before;
        obj['after'] = after;
    }

    /**
     * Constructs a <code>ProtocolDueDateUpdateHistory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProtocolDueDateUpdateHistory} obj Optional instance to populate.
     * @return {module:model/ProtocolDueDateUpdateHistory} The populated <code>ProtocolDueDateUpdateHistory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProtocolDueDateUpdateHistory();

            if (data.hasOwnProperty('user_name')) {
                obj['user_name'] = ApiClient.convertToType(data['user_name'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('created_at_unix_time')) {
                obj['created_at_unix_time'] = ApiClient.convertToType(data['created_at_unix_time'], 'Number');
            }
            if (data.hasOwnProperty('before')) {
                obj['before'] = ApiClient.convertToType(data['before'], Object);
            }
            if (data.hasOwnProperty('after')) {
                obj['after'] = ApiClient.convertToType(data['after'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} user_name
 */
ProtocolDueDateUpdateHistory.prototype['user_name'] = undefined;

/**
 * @member {String} created_at
 */
ProtocolDueDateUpdateHistory.prototype['created_at'] = undefined;

/**
 * @member {Number} created_at_unix_time
 */
ProtocolDueDateUpdateHistory.prototype['created_at_unix_time'] = undefined;

/**
 * @member {Object} before
 */
ProtocolDueDateUpdateHistory.prototype['before'] = undefined;

/**
 * @member {Object} after
 */
ProtocolDueDateUpdateHistory.prototype['after'] = undefined;






export default ProtocolDueDateUpdateHistory;

