/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RollbackSplitsDto model module.
 * @module model/RollbackSplitsDto
 * @version 1.0
 */
class RollbackSplitsDto {
    /**
     * Constructs a new <code>RollbackSplitsDto</code>.
     * @alias module:model/RollbackSplitsDto
     * @param saleIds {Array.<String>} 
     */
    constructor(saleIds) { 
        
        RollbackSplitsDto.initialize(this, saleIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, saleIds) { 
        obj['saleIds'] = saleIds;
    }

    /**
     * Constructs a <code>RollbackSplitsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RollbackSplitsDto} obj Optional instance to populate.
     * @return {module:model/RollbackSplitsDto} The populated <code>RollbackSplitsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RollbackSplitsDto();

            if (data.hasOwnProperty('saleIds')) {
                obj['saleIds'] = ApiClient.convertToType(data['saleIds'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} saleIds
 */
RollbackSplitsDto.prototype['saleIds'] = undefined;






export default RollbackSplitsDto;

