/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SalesHistoryTablePermissions model module.
 * @module model/SalesHistoryTablePermissions
 * @version 1.0
 */
class SalesHistoryTablePermissions {
    /**
     * Constructs a new <code>SalesHistoryTablePermissions</code>.
     * @alias module:model/SalesHistoryTablePermissions
     * @param table {Number} 
     * @param fields {Array.<module:model/SalesHistoryTablePermissions.FieldsEnum>} 
     * @param denied_fields {Array.<module:model/SalesHistoryTablePermissions.DeniedFieldsEnum>} 
     * @param allowed_fields {Array.<module:model/SalesHistoryTablePermissions.AllowedFieldsEnum>} 
     */
    constructor(table, fields, denied_fields, allowed_fields) { 
        
        SalesHistoryTablePermissions.initialize(this, table, fields, denied_fields, allowed_fields);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, table, fields, denied_fields, allowed_fields) { 
        obj['table'] = table;
        obj['fields'] = fields;
        obj['denied_fields'] = denied_fields;
        obj['allowed_fields'] = allowed_fields;
    }

    /**
     * Constructs a <code>SalesHistoryTablePermissions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SalesHistoryTablePermissions} obj Optional instance to populate.
     * @return {module:model/SalesHistoryTablePermissions} The populated <code>SalesHistoryTablePermissions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SalesHistoryTablePermissions();

            if (data.hasOwnProperty('table')) {
                obj['table'] = ApiClient.convertToType(data['table'], 'Number');
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], ['String']);
            }
            if (data.hasOwnProperty('denied_fields')) {
                obj['denied_fields'] = ApiClient.convertToType(data['denied_fields'], ['String']);
            }
            if (data.hasOwnProperty('allowed_fields')) {
                obj['allowed_fields'] = ApiClient.convertToType(data['allowed_fields'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} table
 */
SalesHistoryTablePermissions.prototype['table'] = undefined;

/**
 * @member {Array.<module:model/SalesHistoryTablePermissions.FieldsEnum>} fields
 */
SalesHistoryTablePermissions.prototype['fields'] = undefined;

/**
 * @member {Array.<module:model/SalesHistoryTablePermissions.DeniedFieldsEnum>} denied_fields
 */
SalesHistoryTablePermissions.prototype['denied_fields'] = undefined;

/**
 * @member {Array.<module:model/SalesHistoryTablePermissions.AllowedFieldsEnum>} allowed_fields
 */
SalesHistoryTablePermissions.prototype['allowed_fields'] = undefined;





/**
 * Allowed values for the <code>fields</code> property.
 * @enum {String}
 * @readonly
 */
SalesHistoryTablePermissions['FieldsEnum'] = {

    /**
     * value: "id"
     * @const
     */
    "id": "id",

    /**
     * value: "status"
     * @const
     */
    "status": "status",

    /**
     * value: "payment_method"
     * @const
     */
    "payment_method": "payment_method",

    /**
     * value: "formatted_description"
     * @const
     */
    "formatted_description": "formatted_description",

    /**
     * value: "formatted_protocol"
     * @const
     */
    "formatted_protocol": "formatted_protocol",

    /**
     * value: "generate_payer"
     * @const
     */
    "generate_payer": "generate_payer",

    /**
     * value: "payer"
     * @const
     */
    "payer": "payer",

    /**
     * value: "created_at"
     * @const
     */
    "created_at": "created_at",

    /**
     * value: "payment_day"
     * @const
     */
    "payment_day": "payment_day",

    /**
     * value: "financial"
     * @const
     */
    "financial": "financial",

    /**
     * value: "expiration_day"
     * @const
     */
    "expiration_day": "expiration_day",

    /**
     * value: "settlement_day"
     * @const
     */
    "settlement_day": "settlement_day",

    /**
     * value: "form_payment"
     * @const
     */
    "form_payment": "form_payment",

    /**
     * value: "original_amount"
     * @const
     */
    "original_amount": "original_amount",

    /**
     * value: "amount"
     * @const
     */
    "amount": "amount",

    /**
     * value: "seller_name"
     * @const
     */
    "seller_name": "seller_name",

    /**
     * value: "has_split_rules"
     * @const
     */
    "has_split_rules": "has_split_rules",

    /**
     * value: "payer_email"
     * @const
     */
    "payer_email": "payer_email",

    /**
     * value: "payer_phone"
     * @const
     */
    "payer_phone": "payer_phone",

    /**
     * value: "confirmation_day"
     * @const
     */
    "confirmation_day": "confirmation_day"
};


/**
 * Allowed values for the <code>denied_fields</code> property.
 * @enum {String}
 * @readonly
 */
SalesHistoryTablePermissions['DeniedFieldsEnum'] = {

    /**
     * value: "id"
     * @const
     */
    "id": "id",

    /**
     * value: "status"
     * @const
     */
    "status": "status",

    /**
     * value: "payment_method"
     * @const
     */
    "payment_method": "payment_method",

    /**
     * value: "formatted_description"
     * @const
     */
    "formatted_description": "formatted_description",

    /**
     * value: "formatted_protocol"
     * @const
     */
    "formatted_protocol": "formatted_protocol",

    /**
     * value: "generate_payer"
     * @const
     */
    "generate_payer": "generate_payer",

    /**
     * value: "payer"
     * @const
     */
    "payer": "payer",

    /**
     * value: "created_at"
     * @const
     */
    "created_at": "created_at",

    /**
     * value: "payment_day"
     * @const
     */
    "payment_day": "payment_day",

    /**
     * value: "financial"
     * @const
     */
    "financial": "financial",

    /**
     * value: "expiration_day"
     * @const
     */
    "expiration_day": "expiration_day",

    /**
     * value: "settlement_day"
     * @const
     */
    "settlement_day": "settlement_day",

    /**
     * value: "form_payment"
     * @const
     */
    "form_payment": "form_payment",

    /**
     * value: "original_amount"
     * @const
     */
    "original_amount": "original_amount",

    /**
     * value: "amount"
     * @const
     */
    "amount": "amount",

    /**
     * value: "seller_name"
     * @const
     */
    "seller_name": "seller_name",

    /**
     * value: "has_split_rules"
     * @const
     */
    "has_split_rules": "has_split_rules",

    /**
     * value: "payer_email"
     * @const
     */
    "payer_email": "payer_email",

    /**
     * value: "payer_phone"
     * @const
     */
    "payer_phone": "payer_phone",

    /**
     * value: "confirmation_day"
     * @const
     */
    "confirmation_day": "confirmation_day"
};


/**
 * Allowed values for the <code>allowed_fields</code> property.
 * @enum {String}
 * @readonly
 */
SalesHistoryTablePermissions['AllowedFieldsEnum'] = {

    /**
     * value: "id"
     * @const
     */
    "id": "id",

    /**
     * value: "status"
     * @const
     */
    "status": "status",

    /**
     * value: "payment_method"
     * @const
     */
    "payment_method": "payment_method",

    /**
     * value: "formatted_description"
     * @const
     */
    "formatted_description": "formatted_description",

    /**
     * value: "formatted_protocol"
     * @const
     */
    "formatted_protocol": "formatted_protocol",

    /**
     * value: "generate_payer"
     * @const
     */
    "generate_payer": "generate_payer",

    /**
     * value: "payer"
     * @const
     */
    "payer": "payer",

    /**
     * value: "created_at"
     * @const
     */
    "created_at": "created_at",

    /**
     * value: "payment_day"
     * @const
     */
    "payment_day": "payment_day",

    /**
     * value: "financial"
     * @const
     */
    "financial": "financial",

    /**
     * value: "expiration_day"
     * @const
     */
    "expiration_day": "expiration_day",

    /**
     * value: "settlement_day"
     * @const
     */
    "settlement_day": "settlement_day",

    /**
     * value: "form_payment"
     * @const
     */
    "form_payment": "form_payment",

    /**
     * value: "original_amount"
     * @const
     */
    "original_amount": "original_amount",

    /**
     * value: "amount"
     * @const
     */
    "amount": "amount",

    /**
     * value: "seller_name"
     * @const
     */
    "seller_name": "seller_name",

    /**
     * value: "has_split_rules"
     * @const
     */
    "has_split_rules": "has_split_rules",

    /**
     * value: "payer_email"
     * @const
     */
    "payer_email": "payer_email",

    /**
     * value: "payer_phone"
     * @const
     */
    "payer_phone": "payer_phone",

    /**
     * value: "confirmation_day"
     * @const
     */
    "confirmation_day": "confirmation_day"
};



export default SalesHistoryTablePermissions;

