/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DiscountBankAccount from './DiscountBankAccount';
import Merchant from './Merchant';
import Seller from './Seller';

/**
 * The SettlementBatch model module.
 * @module model/SettlementBatch
 * @version 1.0
 */
class SettlementBatch {
    /**
     * Constructs a new <code>SettlementBatch</code>.
     * @alias module:model/SettlementBatch
     * @param status {module:model/SettlementBatch.StatusEnum} 
     * @param settlement_day {Date} 
     * @param settlement_date {Date} 
     * @param type {module:model/SettlementBatch.TypeEnum} 
     * @param discount_bank_account_id {String} 
     * @param total {Number} 
     * @param is_retry {Boolean} 
     */
    constructor(status, settlement_day, settlement_date, type, discount_bank_account_id, total, is_retry) { 
        
        SettlementBatch.initialize(this, status, settlement_day, settlement_date, type, discount_bank_account_id, total, is_retry);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status, settlement_day, settlement_date, type, discount_bank_account_id, total, is_retry) { 
        obj['status'] = status;
        obj['settlement_day'] = settlement_day;
        obj['settlement_date'] = settlement_date;
        obj['type'] = type;
        obj['discount_bank_account_id'] = discount_bank_account_id;
        obj['total'] = total;
        obj['is_retry'] = is_retry;
    }

    /**
     * Constructs a <code>SettlementBatch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SettlementBatch} obj Optional instance to populate.
     * @return {module:model/SettlementBatch} The populated <code>SettlementBatch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SettlementBatch();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('seller')) {
                obj['seller'] = Seller.constructFromObject(data['seller']);
            }
            if (data.hasOwnProperty('seller_id')) {
                obj['seller_id'] = ApiClient.convertToType(data['seller_id'], 'String');
            }
            if (data.hasOwnProperty('seller_name')) {
                obj['seller_name'] = ApiClient.convertToType(data['seller_name'], 'String');
            }
            if (data.hasOwnProperty('seller_document')) {
                obj['seller_document'] = ApiClient.convertToType(data['seller_document'], 'String');
            }
            if (data.hasOwnProperty('merchant')) {
                obj['merchant'] = Merchant.constructFromObject(data['merchant']);
            }
            if (data.hasOwnProperty('merchant_id')) {
                obj['merchant_id'] = ApiClient.convertToType(data['merchant_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('settlement_day')) {
                obj['settlement_day'] = ApiClient.convertToType(data['settlement_day'], 'Date');
            }
            if (data.hasOwnProperty('settlement_date')) {
                obj['settlement_date'] = ApiClient.convertToType(data['settlement_date'], 'Date');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('discount_bank_account_id')) {
                obj['discount_bank_account_id'] = ApiClient.convertToType(data['discount_bank_account_id'], 'String');
            }
            if (data.hasOwnProperty('discount_bank_account')) {
                obj['discount_bank_account'] = DiscountBankAccount.constructFromObject(data['discount_bank_account']);
            }
            if (data.hasOwnProperty('total_spread')) {
                obj['total_spread'] = ApiClient.convertToType(data['total_spread'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('cnab_id')) {
                obj['cnab_id'] = ApiClient.convertToType(data['cnab_id'], 'String');
            }
            if (data.hasOwnProperty('cnab_filename')) {
                obj['cnab_filename'] = ApiClient.convertToType(data['cnab_filename'], 'String');
            }
            if (data.hasOwnProperty('is_retry')) {
                obj['is_retry'] = ApiClient.convertToType(data['is_retry'], 'Boolean');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('registered_omie')) {
                obj['registered_omie'] = ApiClient.convertToType(data['registered_omie'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
SettlementBatch.prototype['id'] = undefined;

/**
 * @member {module:model/Seller} seller
 */
SettlementBatch.prototype['seller'] = undefined;

/**
 * @member {String} seller_id
 */
SettlementBatch.prototype['seller_id'] = undefined;

/**
 * @member {String} seller_name
 */
SettlementBatch.prototype['seller_name'] = undefined;

/**
 * @member {String} seller_document
 */
SettlementBatch.prototype['seller_document'] = undefined;

/**
 * @member {module:model/Merchant} merchant
 */
SettlementBatch.prototype['merchant'] = undefined;

/**
 * @member {String} merchant_id
 */
SettlementBatch.prototype['merchant_id'] = undefined;

/**
 * @member {module:model/SettlementBatch.StatusEnum} status
 */
SettlementBatch.prototype['status'] = undefined;

/**
 * @member {Date} settlement_day
 */
SettlementBatch.prototype['settlement_day'] = undefined;

/**
 * @member {Date} settlement_date
 */
SettlementBatch.prototype['settlement_date'] = undefined;

/**
 * @member {module:model/SettlementBatch.TypeEnum} type
 */
SettlementBatch.prototype['type'] = undefined;

/**
 * @member {String} discount_bank_account_id
 */
SettlementBatch.prototype['discount_bank_account_id'] = undefined;

/**
 * @member {module:model/DiscountBankAccount} discount_bank_account
 */
SettlementBatch.prototype['discount_bank_account'] = undefined;

/**
 * @member {Number} total_spread
 */
SettlementBatch.prototype['total_spread'] = undefined;

/**
 * @member {Number} total
 */
SettlementBatch.prototype['total'] = undefined;

/**
 * @member {String} cnab_id
 */
SettlementBatch.prototype['cnab_id'] = undefined;

/**
 * @member {String} cnab_filename
 */
SettlementBatch.prototype['cnab_filename'] = undefined;

/**
 * @member {Boolean} is_retry
 */
SettlementBatch.prototype['is_retry'] = undefined;

/**
 * @member {String} created_at
 */
SettlementBatch.prototype['created_at'] = undefined;

/**
 * @member {String} updated_at
 */
SettlementBatch.prototype['updated_at'] = undefined;

/**
 * @member {Boolean} registered_omie
 */
SettlementBatch.prototype['registered_omie'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
SettlementBatch['StatusEnum'] = {

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "paid"
     * @const
     */
    "paid": "paid",

    /**
     * value: "sent"
     * @const
     */
    "sent": "sent",

    /**
     * value: "pending_cancel"
     * @const
     */
    "pending_cancel": "pending_cancel",

    /**
     * value: "canceled"
     * @const
     */
    "canceled": "canceled",

    /**
     * value: "failed"
     * @const
     */
    "failed": "failed",

    /**
     * value: "resent"
     * @const
     */
    "resent": "resent"
};


/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
SettlementBatch['TypeEnum'] = {

    /**
     * value: "PIX"
     * @const
     */
    "PIX": "PIX",

    /**
     * value: "TED"
     * @const
     */
    "TED": "TED"
};



export default SettlementBatch;

