/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdatePaymentLinkDto model module.
 * @module model/UpdatePaymentLinkDto
 * @version 1.0
 */
class UpdatePaymentLinkDto {
    /**
     * Constructs a new <code>UpdatePaymentLinkDto</code>.
     * @alias module:model/UpdatePaymentLinkDto
     * @param expiresIn {Boolean} Data de vencimento
     */
    constructor(expiresIn) { 
        
        UpdatePaymentLinkDto.initialize(this, expiresIn);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, expiresIn) { 
        obj['expiresIn'] = expiresIn;
    }

    /**
     * Constructs a <code>UpdatePaymentLinkDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdatePaymentLinkDto} obj Optional instance to populate.
     * @return {module:model/UpdatePaymentLinkDto} The populated <code>UpdatePaymentLinkDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdatePaymentLinkDto();

            if (data.hasOwnProperty('expiresIn')) {
                obj['expiresIn'] = ApiClient.convertToType(data['expiresIn'], 'Boolean');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Data de vencimento
 * @member {Boolean} expiresIn
 */
UpdatePaymentLinkDto.prototype['expiresIn'] = undefined;

/**
 * @member {module:model/UpdatePaymentLinkDto.StatusEnum} status
 */
UpdatePaymentLinkDto.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
UpdatePaymentLinkDto['StatusEnum'] = {

    /**
     * value: "active"
     * @const
     */
    "active": "active",

    /**
     * value: "pending_capture"
     * @const
     */
    "pending_capture": "pending_capture",

    /**
     * value: "expired"
     * @const
     */
    "expired": "expired",

    /**
     * value: "canceled"
     * @const
     */
    "canceled": "canceled",

    /**
     * value: "paid"
     * @const
     */
    "paid": "paid"
};



export default UpdatePaymentLinkDto;

