/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Permission from './Permission';

/**
 * The UpdateRoleDto model module.
 * @module model/UpdateRoleDto
 * @version 1.0
 */
class UpdateRoleDto {
    /**
     * Constructs a new <code>UpdateRoleDto</code>.
     * @alias module:model/UpdateRoleDto
     */
    constructor() { 
        
        UpdateRoleDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateRoleDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateRoleDto} obj Optional instance to populate.
     * @return {module:model/UpdateRoleDto} The populated <code>UpdateRoleDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateRoleDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], [Permission]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
UpdateRoleDto.prototype['name'] = undefined;

/**
 * @member {module:model/UpdateRoleDto.TypeEnum} type
 */
UpdateRoleDto.prototype['type'] = undefined;

/**
 * @member {Array.<module:model/Permission>} permissions
 */
UpdateRoleDto.prototype['permissions'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
UpdateRoleDto['TypeEnum'] = {

    /**
     * value: "merchant"
     * @const
     */
    "merchant": "merchant",

    /**
     * value: "seller"
     * @const
     */
    "seller": "seller",

    /**
     * value: "backoffice"
     * @const
     */
    "backoffice": "backoffice"
};



export default UpdateRoleDto;

