/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UpdatePaymentLinkDto model module.
 * @module model/UpdatePaymentLinkDto
 * @version 1.0
 */
export class UpdatePaymentLinkDto {
  /**
   * Constructs a new <code>UpdatePaymentLinkDto</code>.
   * @alias module:model/UpdatePaymentLinkDto
   * @class
   * @param expiresIn {Boolean} 
   */
  constructor(expiresIn) {
    this.expiresIn = expiresIn;
  }

  /**
   * Constructs a <code>UpdatePaymentLinkDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdatePaymentLinkDto} obj Optional instance to populate.
   * @return {module:model/UpdatePaymentLinkDto} The populated <code>UpdatePaymentLinkDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdatePaymentLinkDto();
      if (data.hasOwnProperty('expiresIn'))
        obj.expiresIn = ApiClient.convertToType(data['expiresIn'], 'Boolean');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Boolean} expiresIn
 */
UpdatePaymentLinkDto.prototype.expiresIn = undefined;

/**
 * @member {String} status
 */
UpdatePaymentLinkDto.prototype.status = undefined;

