/*
 * Parcela Express API
 * Parcela Express API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserRefreshTokenDto model module.
 * @module model/UserRefreshTokenDto
 * @version 1.0
 */
export class UserRefreshTokenDto {
  /**
   * Constructs a new <code>UserRefreshTokenDto</code>.
   * @alias module:model/UserRefreshTokenDto
   * @class
   * @param refreshToken {String} 
   */
  constructor(refreshToken) {
    this.refreshToken = refreshToken;
  }

  /**
   * Constructs a <code>UserRefreshTokenDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserRefreshTokenDto} obj Optional instance to populate.
   * @return {module:model/UserRefreshTokenDto} The populated <code>UserRefreshTokenDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserRefreshTokenDto();
      if (data.hasOwnProperty('refresh_token'))
        obj.refreshToken = ApiClient.convertToType(data['refresh_token'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} refreshToken
 */
UserRefreshTokenDto.prototype.refreshToken = undefined;

