/**
 * Parcela Express API
 * Parcela Express API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserRefreshTokenResponseDto model module.
 * @module model/UserRefreshTokenResponseDto
 * @version 1.0
 */
class UserRefreshTokenResponseDto {
    /**
     * Constructs a new <code>UserRefreshTokenResponseDto</code>.
     * @alias module:model/UserRefreshTokenResponseDto
     * @param refresh_token {String} 
     * @param id_token {String} 
     */
    constructor(refresh_token, id_token) { 
        
        UserRefreshTokenResponseDto.initialize(this, refresh_token, id_token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, refresh_token, id_token) { 
        obj['refresh_token'] = refresh_token;
        obj['id_token'] = id_token;
    }

    /**
     * Constructs a <code>UserRefreshTokenResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserRefreshTokenResponseDto} obj Optional instance to populate.
     * @return {module:model/UserRefreshTokenResponseDto} The populated <code>UserRefreshTokenResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserRefreshTokenResponseDto();

            if (data.hasOwnProperty('refresh_token')) {
                obj['refresh_token'] = ApiClient.convertToType(data['refresh_token'], 'String');
            }
            if (data.hasOwnProperty('id_token')) {
                obj['id_token'] = ApiClient.convertToType(data['id_token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} refresh_token
 */
UserRefreshTokenResponseDto.prototype['refresh_token'] = undefined;

/**
 * @member {String} id_token
 */
UserRefreshTokenResponseDto.prototype['id_token'] = undefined;






export default UserRefreshTokenResponseDto;

